using Alis.Reactive.PlanModel;

namespace Alis.Reactive
{
    /// <summary>
    /// Immutable registration of a component in the reactive plan.
    /// Populated at view render time by each vertical slice's HtmlExtensions.
    /// Consumed by gather (HTTP serialization) and validation (field enrichment).
    /// </summary>
    internal sealed class ComponentRegistration
    {
        /// <summary>DOM element ID generated by IdGenerator from the model expression.</summary>
        public string ComponentId { get; }

        /// <summary>"native" or "fusion" — determines resolution strategy at runtime.</summary>
        public string Vendor { get; }

        /// <summary>Model property path (e.g., "AdmissionDate", "Address.Street") — key in ComponentsMap.</summary>
        public string BindingPath { get; }

        /// <summary>Dot-path from vendor root to the readable value (e.g., "value", "checked").</summary>
        public string ValueMember { get; }

        /// <summary>Semantic component kind (e.g., "datepicker", "numerictextbox").</summary>
        public string ComponentType { get; }

        /// <summary>
        /// Shape inferred from typeof(TProp) at registration time.
        /// Flows to plan JSON — consumed by gather (serialization) and validation (field enrichment).
        /// </summary>
        public Shape Shape { get; }

        internal ComponentRegistration(string componentId, string vendor, string bindingPath, string valueMember, string componentType, Shape shape)
        {
            ComponentId = componentId;
            Vendor = vendor;
            BindingPath = bindingPath;
            ValueMember = valueMember;
            ComponentType = componentType;
            Shape = shape;
        }
    }
}
