using System.Collections.Generic;
using Alis.Reactive.PlanModel;

namespace Alis.Reactive
{
    /// <summary>
    /// Immutable registration of a component in the reactive plan.
    /// Populated at view render time by each vertical slice's HtmlExtensions.
    /// Consumed by gather (HTTP serialization) and validation field binding.
    /// </summary>
    public sealed class ComponentRegistration
    {
        private readonly RegisteredComponentIdentity _identity;
        private readonly RegisteredComponentBinding _binding;
        private readonly ComponentKind _componentType;
        private readonly ComponentRegistrationContract _contract;

        /// <summary>DOM element ID generated by IdGenerator from the model expression.</summary>
        public string ComponentId => _identity.ComponentId.Value;

        /// <summary>"native" or "fusion" — determines resolution strategy at runtime.</summary>
        public string Vendor => _identity.Vendor.Value;

        /// <summary>Model property path (e.g., "AdmissionDate", "Address.Street") — key in the input component onboarding catalog.</summary>
        public string BindingPath => _binding.BindingPath.Value;

        /// <summary>Dot-path from vendor root to the readable value (e.g., "value", "checked").</summary>
        public string ValueMember => _binding.ValueMember.Value;

        /// <summary>Semantic component kind (e.g., "datepicker", "numerictextbox").</summary>
        public string ComponentType => _componentType.Value;

        /// <summary>
        /// Shape inferred from typeof(TProp) at registration time.
        /// Flows to plan JSON and is consumed by gather serialization and validation binding.
        /// </summary>
        public Shape Shape { get; }

        internal InputValueContract ValueContract =>
            InputValueContract.For(_binding.ValueMember, Shape);

        internal BindingPath RegisteredBindingPath => _binding.BindingPath;

        internal InputComponentPlanBinding PlanBinding =>
            InputComponentPlanBinding.For(
                _identity.ComponentId,
                _identity.Vendor,
                _binding.BindingPath,
                ValueContract);

        internal InputValueContract RequireValueContract(MemberName expectedValueMember)
        {
            if (expectedValueMember == null) throw new System.ArgumentNullException(nameof(expectedValueMember));
            if (!_binding.ValueMember.Equals(expectedValueMember))
                throw new System.InvalidOperationException(
                    $"Component '{ComponentId}' is registered for binding path '{BindingPath}' " +
                    $"with value member '{_binding.ValueMember.Value}', but this usage requested " +
                    $"'{expectedValueMember.Value}'. Use the component type that matches the rendered input.");

            return ValueContract;
        }

        internal string DescribeContract() =>
            _contract.Describe();

        internal bool HasSameContractAs(ComponentRegistration other)
        {
            if (other == null) throw new System.ArgumentNullException(nameof(other));
            return _contract.Matches(other._contract);
        }

        private ComponentRegistration(
            RegisteredComponentIdentity identity,
            RegisteredComponentBinding binding,
            ComponentKind componentType,
            Shape shape)
        {
            _identity = identity ?? throw new System.ArgumentNullException(nameof(identity));
            _binding = binding ?? throw new System.ArgumentNullException(nameof(binding));
            _componentType = componentType ?? throw new System.ArgumentNullException(nameof(componentType));
            Shape = shape ?? throw new System.ArgumentNullException(nameof(shape));
            _contract = ComponentRegistrationContract.From(
                _identity,
                _binding,
                _componentType,
                Shape);
        }

        internal static ComponentRegistration RegisteredInput(
            RegisteredComponentIdentity identity,
            RegisteredComponentBinding binding,
            ComponentKind componentType,
            Shape shape) =>
            new ComponentRegistration(identity, binding, componentType, shape);
    }

    internal sealed class ComponentRegistrationContract
    {
        private readonly RegisteredComponentIdentity _identity;
        private readonly RegisteredComponentBinding _binding;
        private readonly ComponentKind _componentType;
        private readonly Shape _shape;

        private ComponentRegistrationContract(
            RegisteredComponentIdentity identity,
            RegisteredComponentBinding binding,
            ComponentKind componentType,
            Shape shape)
        {
            _identity = identity ?? throw new System.ArgumentNullException(nameof(identity));
            _binding = binding ?? throw new System.ArgumentNullException(nameof(binding));
            _componentType = componentType ?? throw new System.ArgumentNullException(nameof(componentType));
            _shape = shape ?? throw new System.ArgumentNullException(nameof(shape));
        }

        internal static ComponentRegistrationContract From(
            RegisteredComponentIdentity identity,
            RegisteredComponentBinding binding,
            ComponentKind componentType,
            Shape shape) =>
            new ComponentRegistrationContract(identity, binding, componentType, shape);

        internal bool Matches(ComponentRegistrationContract other)
        {
            if (other == null) throw new System.ArgumentNullException(nameof(other));

            var identityMatches = _identity.Matches(other._identity);
            var bindingMatches = _binding.Matches(other._binding);
            var componentTypeMatches = _componentType.Equals(other._componentType);
            var shapeMatches = _shape == other._shape;
            return identityMatches && bindingMatches && componentTypeMatches && shapeMatches;
        }

        internal string Describe() =>
            $"[{_identity.ComponentId.Value}, {_identity.Vendor.Value}, {_binding.ValueMember.Value}, {_componentType.Value}, {_shape.DescribeContract()}]";
    }

    internal sealed class ComponentRegistrationCatalog
    {
        private readonly Dictionary<string, ComponentRegistration> _registrations =
            new Dictionary<string, ComponentRegistration>(System.StringComparer.Ordinal);

        internal IReadOnlyDictionary<string, ComponentRegistration> Snapshot() =>
            new Dictionary<string, ComponentRegistration>(_registrations, System.StringComparer.Ordinal);

        internal IReadOnlyList<KeyValuePair<string, ComponentRegistration>> Entries =>
            new List<KeyValuePair<string, ComponentRegistration>>(_registrations);

        internal bool Contains(BindingPath bindingPath)
        {
            if (bindingPath == null) throw new System.ArgumentNullException(nameof(bindingPath));
            return _registrations.ContainsKey(bindingPath.Value);
        }

        internal void Add(BindingPath bindingPath, ComponentRegistration registration)
        {
            if (bindingPath == null) throw new System.ArgumentNullException(nameof(bindingPath));
            if (registration == null) throw new System.ArgumentNullException(nameof(registration));

            if (_registrations.TryGetValue(bindingPath.Value, out var existing))
            {
                var duplicateRegistrationIsIdempotent = existing.HasSameContractAs(registration);
                if (duplicateRegistrationIsIdempotent)
                    return;

                throw DuplicateRegistration(bindingPath, existing, registration);
            }

            EnsureComponentIdentityIsUnused(bindingPath, registration);
            _registrations[bindingPath.Value] = registration;
        }

        internal ComponentRegistrationMatch FindForComponent(ComponentId componentId)
        {
            if (componentId == null) throw new System.ArgumentNullException(nameof(componentId));

            if (_registrations.TryGetValue(componentId.Value, out var exactBindingMatch))
            {
                var registrationTargetsRequestedComponent = exactBindingMatch.ComponentId == componentId.Value;
                if (registrationTargetsRequestedComponent)
                    return ComponentRegistrationMatch.Found(exactBindingMatch);
            }

            foreach (var registration in _registrations.Values)
            {
                if (registration.ComponentId == componentId.Value)
                    return ComponentRegistrationMatch.Found(registration);
            }

            return ComponentRegistrationMatch.Missing();
        }

        private void EnsureComponentIdentityIsUnused(
            BindingPath incomingBindingPath,
            ComponentRegistration incoming)
        {
            foreach (var existing in _registrations)
            {
                var componentIdAlreadyRegistered = string.Equals(
                    existing.Value.ComponentId,
                    incoming.ComponentId,
                    System.StringComparison.Ordinal);

                if (componentIdAlreadyRegistered)
                    throw DuplicateComponentIdentity(
                        BindingPath.Of(existing.Key),
                        existing.Value,
                        incomingBindingPath,
                        incoming);
            }
        }

        private static System.InvalidOperationException DuplicateRegistration(
            BindingPath bindingPath,
            ComponentRegistration existing,
            ComponentRegistration incoming)
        {
            return new System.InvalidOperationException(
                $"Duplicate component registration for binding path '{bindingPath.Value}': " +
                $"existing {existing.DescribeContract()} vs " +
                $"new {incoming.DescribeContract()}.");
        }

        private static System.InvalidOperationException DuplicateComponentIdentity(
            BindingPath existingBindingPath,
            ComponentRegistration existing,
            BindingPath incomingBindingPath,
            ComponentRegistration incoming)
        {
            return new System.InvalidOperationException(
                $"Component id '{incoming.ComponentId}' is already registered for binding path " +
                $"'{existingBindingPath.Value}' and cannot also be registered for " +
                $"'{incomingBindingPath.Value}': existing {existing.DescribeContract()} vs " +
                $"new {incoming.DescribeContract()}.");
        }
    }

    internal sealed class InputComponentRegistrationProfile
    {
        private readonly IInputComponent _component;
        private readonly ComponentKind _componentType;

        private InputComponentRegistrationProfile(IInputComponent component, ComponentKind componentType)
        {
            _component = component ?? throw new System.ArgumentNullException(nameof(component));
            _componentType = componentType ?? throw new System.ArgumentNullException(nameof(componentType));
        }

        internal string Vendor => _component.Vendor;

        internal string ValueMember => _component.ValueMember;

        internal ComponentRegistration Register(ModelBoundInputComponentSlot slot)
        {
            if (slot == null) throw new System.ArgumentNullException(nameof(slot));

            var identity = RegisteredComponentIdentity.For(slot.ComponentId, ComponentVendor.From(_component.Vendor));
            var binding = RegisteredComponentBinding.For(slot.BindingPath, MemberName.Of(_component.ValueMember));
            return ComponentRegistration.RegisteredInput(identity, binding, _componentType, slot.ValueShape);
        }

        internal static InputComponentRegistrationProfile For(
            IInputComponent component,
            string componentType) =>
            new InputComponentRegistrationProfile(component, ComponentKind.Of(componentType));
    }

    internal sealed class RegisteredComponentIdentity
    {
        private RegisteredComponentIdentity(ComponentId componentId, ComponentVendor vendor)
        {
            ComponentId = componentId ?? throw new System.ArgumentNullException(nameof(componentId));
            Vendor = vendor ?? throw new System.ArgumentNullException(nameof(vendor));
        }

        internal ComponentId ComponentId { get; }
        internal ComponentVendor Vendor { get; }

        internal bool Matches(RegisteredComponentIdentity other)
        {
            if (other == null) throw new System.ArgumentNullException(nameof(other));
            return ComponentId.Equals(other.ComponentId) && Vendor.Equals(other.Vendor);
        }

        internal static RegisteredComponentIdentity For(string componentId, string vendor) =>
            new RegisteredComponentIdentity(
                Alis.Reactive.PlanModel.ComponentId.Of(componentId),
                ComponentVendor.From(vendor));

        internal static RegisteredComponentIdentity For(ComponentId componentId, ComponentVendor vendor) =>
            new RegisteredComponentIdentity(componentId, vendor);
    }

    internal sealed class RegisteredComponentBinding
    {
        private RegisteredComponentBinding(BindingPath bindingPath, MemberName valueMember)
        {
            BindingPath = bindingPath ?? throw new System.ArgumentNullException(nameof(bindingPath));
            ValueMember = valueMember ?? throw new System.ArgumentNullException(nameof(valueMember));
        }

        internal BindingPath BindingPath { get; }
        internal MemberName ValueMember { get; }

        internal bool Matches(RegisteredComponentBinding other)
        {
            if (other == null) throw new System.ArgumentNullException(nameof(other));
            return BindingPath.Equals(other.BindingPath) && ValueMember.Equals(other.ValueMember);
        }

        internal static RegisteredComponentBinding For(string bindingPath, string valueMember) =>
            new RegisteredComponentBinding(
                Alis.Reactive.PlanModel.BindingPath.Of(bindingPath),
                MemberName.Of(valueMember));

        internal static RegisteredComponentBinding For(BindingPath bindingPath, MemberName valueMember) =>
            new RegisteredComponentBinding(bindingPath, valueMember);
    }
}
