namespace Alis.Reactive
{
    /// <summary>
    /// Immutable registration of a component in the reactive plan.
    /// Populated at view render time by each vertical slice's HtmlExtensions.
    /// Consumed by plan authoring when it shapes bindings, gather payloads, and validation metadata.
    /// </summary>
    public sealed class ComponentRegistration
    {
        /// <summary>DOM element ID generated by IdGenerator from the model expression.</summary>
        public string ComponentId { get; }

        /// <summary>"native" or "fusion" — determines the runtime root-resolution strategy.</summary>
        public string Vendor { get; }

        /// <summary>Model property path (e.g., "AdmissionDate", "Address.Street") — key in RegisteredComponents.</summary>
        public string BindingPath { get; }

        /// <summary>Dot-path from the component root to the readable value (e.g., "value", "checked").</summary>
        public string ValueMemberPath { get; }

        /// <summary>Semantic component kind (e.g., "datepicker", "numerictextbox") — descriptive, not used for coercion.</summary>
        public string ComponentType { get; }

        /// <summary>
        /// Coercion type inferred from typeof(TProp) via CoercionTypes.InferFromType at registration.
        /// Flows into the authored plan shape for typed gather payloads and validation rules.
        /// Values: "string", "number", "boolean", "date", "array", "raw".
        /// </summary>
        public string CoerceAs { get; }

        /// <summary>
        /// NEVER make public. Constructed exclusively by framework builders. Public constructors
        /// on framework-owned contract types allow devs to bypass the builder API and create invalid plan state.
        /// </summary>
        internal ComponentRegistration(string componentId, string vendor, string bindingPath, string valueMemberPath, string componentType, string coerceAs)
        {
            ComponentId = componentId;
            Vendor = vendor;
            BindingPath = bindingPath;
            ValueMemberPath = valueMemberPath;
            ComponentType = componentType;
            CoerceAs = coerceAs;
        }
    }
}
