using Alis.Reactive.PlanModel;

namespace Alis.Reactive
{
    /// <summary>
    /// Immutable registration of a component in the Reactive Plan.
    /// Populated at view render time by each vertical slice's HtmlExtensions.
    /// Consumed by gather (HTTP serialization) and validation field binding.
    /// </summary>
    public sealed class ComponentRegistration
    {
        private readonly RegisteredComponentIdentity _identity;
        private readonly RegisteredInputBinding _binding;
        private readonly ComponentKind _componentType;

        /// <summary>DOM element ID generated by IdGenerator from the model expression.</summary>
        public string ComponentId => _identity.ComponentId.Value;

        /// <summary>"native" or "fusion" — determines resolution strategy at runtime.</summary>
        public string Vendor => _identity.Vendor.Value;

        /// <summary>Model property path (e.g., "AdmissionDate", "Address.Street") — key in the input component onboarding catalog.</summary>
        public string BindingPath => _binding.BindingPath.Value;

        /// <summary>Dot-path from vendor root to the readable value (e.g., "value", "checked").</summary>
        public string ValueMember => _binding.ValueMember.Value;

        /// <summary>Semantic component kind (e.g., "datepicker", "numerictextbox").</summary>
        public string ComponentType => _componentType.Value;

        /// <summary>
        /// Shape inferred from typeof(TProp) at registration time.
        /// Flows to plan JSON and is consumed by gather serialization and validation binding.
        /// </summary>
        public Shape Shape { get; }

        internal InputValueContract ValueContract =>
            InputValueContract.For(_binding.ValueMember, Shape);

        internal BindingPath RegisteredBindingPath => _binding.BindingPath;

        internal InputComponentPlanBinding PlanBinding =>
            InputComponentPlanBinding.For(
                _identity.ComponentId,
                _identity.Vendor,
                _binding.BindingPath,
                ValueContract);

        internal InputValueContract RequireValueContract(MemberName expectedValueMember)
        {
            if (expectedValueMember == null) throw new System.ArgumentNullException(nameof(expectedValueMember));
            if (!_binding.ValueMember.Equals(expectedValueMember))
                throw new System.InvalidOperationException(
                    $"Component '{ComponentId}' is registered for binding path '{BindingPath}' " +
                    $"with value member '{_binding.ValueMember.Value}', but this usage requested " +
                    $"'{expectedValueMember.Value}'. Use the component type that matches the rendered input.");

            return ValueContract;
        }

        internal void DeclareValueContract(BrowserObjectContracts contracts, BrowserObjectId typeKey)
        {
            if (contracts == null) throw new System.ArgumentNullException(nameof(contracts));
            if (typeKey == null) throw new System.ArgumentNullException(nameof(typeKey));

            contracts.DeclareInputValueContract(typeKey, ValueContract);
        }

        internal BrowserObject CreateComponent(ComponentId componentId, ComponentVendor vendor, BrowserObjectId typeKey)
        {
            if (componentId == null) throw new System.ArgumentNullException(nameof(componentId));
            if (vendor == null) throw new System.ArgumentNullException(nameof(vendor));
            if (typeKey == null) throw new System.ArgumentNullException(nameof(typeKey));

            return BrowserObject.PlanInput(
                componentId,
                vendor,
                typeKey,
                ValueContract.BindingFor(RegisteredBindingPath));
        }

        internal BrowserObject AddBindingTo(BrowserObject component, BrowserObjectContract objectContract)
        {
            if (component == null) throw new System.ArgumentNullException(nameof(component));
            if (objectContract == null) throw new System.ArgumentNullException(nameof(objectContract));

            ValueContract.Enrich(objectContract);
            return component.WithBindingIfAbsent(ValueContract.BindingFor(RegisteredBindingPath));
        }

        internal string DescribeContract() =>
            $"[{_identity.ComponentId.Value}, {_identity.Vendor.Value}, {_binding.ValueMember.Value}, {_componentType.Value}, {Shape.DescribeContract()}]";

        internal bool HasSameContractAs(ComponentRegistration other)
        {
            if (other == null) throw new System.ArgumentNullException(nameof(other));
            return _identity.Matches(other._identity)
                && _binding.Matches(other._binding)
                && _componentType.Equals(other._componentType)
                && Shape == other.Shape;
        }

        private ComponentRegistration(
            RegisteredComponentIdentity identity,
            RegisteredInputBinding binding,
            ComponentKind componentType,
            Shape shape)
        {
            _identity = identity ?? throw new System.ArgumentNullException(nameof(identity));
            _binding = binding ?? throw new System.ArgumentNullException(nameof(binding));
            _componentType = componentType ?? throw new System.ArgumentNullException(nameof(componentType));
            Shape = shape ?? throw new System.ArgumentNullException(nameof(shape));
        }

        internal static ComponentRegistration RegisteredInput(
            RegisteredComponentIdentity identity,
            RegisteredInputBinding binding,
            ComponentKind componentType,
            Shape shape) =>
            new ComponentRegistration(identity, binding, componentType, shape);
    }

}
