// <auto-generated />
// Generated by Alis.Reactive.PlanModel.PlanContractGenerator.
// Do not edit by hand. Run `npm run generate:plan-types -w Alis.Reactive.Assets`.

export interface PlanDocument {
  version: 3;
  planId: string;
  scope: PlanScope;
  types: Record<string, BrowserObjectContract>;
  components: Record<string, ComponentObject>;
  behaviors: Behavior[];
}

export type PlanScope =
  | RootPlanScope
  | PartialPlanScope;

export interface RootPlanScope {
  kind: "root";
}

export interface PartialPlanScope {
  kind: "partial";
}

export interface BrowserObjectContract {
  properties: Record<string, Property>;
  methods: Record<string, Method>;
  events: Record<string, Event>;
}

export interface Property {
  path: Path;
  shape: Shape;
  access: MemberAccess;
}

export type MemberAccess =
  | "read"
  | "write"
  | "readwrite";

export interface Method {
  path: Path;
  arguments: MethodArgumentContract;
  returns: Shape;
}

export type MethodArgumentContract =
  | OpenMethodArgumentContract
  | ExactMethodArgumentContract;

export interface OpenMethodArgumentContract {
  kind: "open";
}

export interface ExactMethodArgumentContract {
  kind: "exact";
  shapes: Shape[];
}

export interface Event {
  channel: string;
}

export type Vendor = string;

export type ComponentObject =
  | ObjectTargetComponent
  | PlanInputComponent
  | ValidationContainerComponentDefinition
  | LayoutObjectComponent;

export interface ObjectTargetComponent {
  id: string;
  vendor: Vendor;
  type: string;
  role: ObjectTargetComponentRole;
  binding: NoInputBinding;
  container: NoValidationContainer;
}

export interface PlanInputComponent {
  id: string;
  vendor: Vendor;
  type: string;
  role: PlanInputComponentRole;
  binding: RegisteredInputBinding;
  container: NoValidationContainer;
}

export interface ValidationContainerComponentDefinition {
  id: string;
  vendor: Vendor;
  type: string;
  role: ValidationContainerComponentRole;
  binding: InputBinding;
  container: ValidationContainerScope;
}

export interface LayoutObjectComponent {
  id: string;
  vendor: Vendor;
  type: string;
  role: LayoutObjectComponentRole;
  binding: NoInputBinding;
  container: NoValidationContainer;
}

export type ComponentRole =
  | ObjectTargetComponentRole
  | PlanInputComponentRole
  | ValidationContainerComponentRole
  | LayoutObjectComponentRole;

export interface ObjectTargetComponentRole {
  kind: "object-target";
}

export interface PlanInputComponentRole {
  kind: "plan-input";
}

export interface ValidationContainerComponentRole {
  kind: "validation-container";
}

export interface LayoutObjectComponentRole {
  kind: "layout-object";
}

export type InputBinding =
  | NoInputBinding
  | RegisteredInputBinding;

export interface NoInputBinding {
  kind: "none";
}

export interface RegisteredInputBinding {
  kind: "registered-input";
  bindingPath: string;
  path: StructuredPath;
  valueMember: string;
}

export type ValidationContainerBinding =
  | NoValidationContainer
  | ValidationContainerScope;

export interface NoValidationContainer {
  kind: "none";
}

export interface ValidationContainerScope {
  kind: "validation-container";
  validationRules: ComponentValidation[];
}

export interface ComponentValidation {
  component: string;
  value: ValueExpression;
  serverFieldName: string;
  rules: ValidationRule[];
}

export type ValidationRuleName =
  | "required"
  | "empty"
  | "minLength"
  | "maxLength"
  | "email"
  | "regex"
  | "url"
  | "creditCard"
  | "range"
  | "exclusiveRange"
  | "min"
  | "max"
  | "gt"
  | "lt"
  | "equalTo"
  | "notEqual"
  | "notEqualTo"
  | "atLeastOne";

export type ValidationRule =
  | NoOperandValidationRule
  | LengthValidationRule
  | RegexValidationRule
  | RangeValidationRule
  | OrderedComparisonValidationRule
  | PeerOrderedComparisonValidationRule
  | LiteralEqualityValidationRule
  | PeerEqualityValidationRule;

export type NoOperandValidationRuleName =
  | "required"
  | "empty"
  | "email"
  | "url"
  | "creditCard"
  | "atLeastOne";

export type LengthValidationRuleName =
  | "minLength"
  | "maxLength";

export type RegexValidationRuleName =
  | "regex";

export type RangeValidationRuleName =
  | "range"
  | "exclusiveRange";

export type OrderedComparisonValidationRuleName =
  | "min"
  | "max"
  | "gt"
  | "lt";

export type PeerOrderedComparisonValidationRuleName =
  | "min"
  | "max"
  | "gt"
  | "lt";

export type LiteralEqualityValidationRuleName =
  | "equalTo"
  | "notEqual";

export type PeerEqualityValidationRuleName =
  | "equalTo"
  | "notEqualTo";

export interface NoOperandValidationRule {
  name: NoOperandValidationRuleName;
  message: string;
  execution: NoOperandValidationRuleExecution;
}

export interface LengthValidationRule {
  name: LengthValidationRuleName;
  message: string;
  execution: NumericConstraintValidationRuleExecution;
}

export interface RegexValidationRule {
  name: RegexValidationRuleName;
  message: string;
  execution: TextConstraintValidationRuleExecution;
}

export interface RangeValidationRule {
  name: RangeValidationRuleName;
  message: string;
  execution: RangeConstraintValidationRuleExecution;
}

export interface OrderedComparisonValidationRule {
  name: OrderedComparisonValidationRuleName;
  message: string;
  execution: ScalarConstraintValidationRuleExecution;
}

export interface PeerOrderedComparisonValidationRule {
  name: PeerOrderedComparisonValidationRuleName;
  message: string;
  execution: PeerValidationRuleExecution;
}

export interface LiteralEqualityValidationRule {
  name: LiteralEqualityValidationRuleName;
  message: string;
  execution: ScalarConstraintValidationRuleExecution;
}

export interface PeerEqualityValidationRule {
  name: PeerEqualityValidationRuleName;
  message: string;
  execution: PeerValidationRuleExecution;
}

export type ValidationRuleExecution =
  | NoOperandValidationRuleExecution
  | ScalarConstraintValidationRuleExecution
  | NumericConstraintValidationRuleExecution
  | TextConstraintValidationRuleExecution
  | RangeConstraintValidationRuleExecution
  | PeerValidationRuleExecution;

export interface NoOperandValidationRuleExecution {
  kind: "none";
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface ScalarConstraintValidationRuleExecution {
  kind: "constraint";
  value: LiteralExpression;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface NumericConstraintValidationRuleExecution {
  kind: "constraint";
  value: NumericLiteralExpression;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface TextConstraintValidationRuleExecution {
  kind: "constraint";
  value: TextLiteralExpression;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface RangeConstraintValidationRuleExecution {
  kind: "constraint";
  value: RangeLiteralExpression;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface PeerValidationRuleExecution {
  kind: "peer";
  value: ReadExpression;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export type ValidationRuleActivation =
  | AlwaysValidationRuleActivation
  | ConditionalValidationRuleActivation;

export interface AlwaysValidationRuleActivation {
  kind: "always";
}

export interface ConditionalValidationRuleActivation {
  kind: "when";
  condition: ValidationCondition;
}

export type Source =
  | ComponentSource
  | PayloadSource
  | UrlSource
  | PluginSource
  | DomSource;

export type RuntimeObjectSource =
  | ComponentSource
  | PluginSource;

export type SetTargetSource =
  | ComponentSource
  | PayloadSource;

export type CallTargetSource =
  | ComponentSource
  | PayloadSource
  | PluginSource;

export interface ComponentSource {
  kind: "component";
  component: string;
}

export interface UrlSource {
  kind: "url";
}

export interface DomSource {
  kind: "dom";
  element: string;
}

export interface PluginSource {
  kind: "plugin";
  name: string;
  type: string;
}

export type PayloadScope =
  | "event"
  | "success"
  | "error"
  | "request"
  | "dispatch"
  | "local"
  | "element";

export interface PayloadSource {
  kind: "payload";
  scope: PayloadScope;
}

export interface Behavior {
  startsWhen: StartsWhen;
  reaction: ReactionGraph;
}

export type StartsWhen =
  | PageReadyTrigger
  | DocumentEventTrigger
  | ComponentEventTrigger
  | ServerPushTrigger
  | SignalRTrigger;

export interface PageReadyTrigger {
  kind: "page-ready";
}

export interface DocumentEventTrigger {
  kind: "document-event";
  event: string;
}

export interface ComponentEventTrigger {
  kind: "component-event";
  component: string;
  event: string;
}

export interface ServerPushTrigger {
  kind: "server-push";
  url: string;
  eventFilter: ServerPushEventFilter;
}

export type ServerPushEventFilter =
  | AnyServerPushEventFilter
  | NamedServerPushEventFilter;

export interface AnyServerPushEventFilter {
  kind: "any";
}

export interface NamedServerPushEventFilter {
  kind: "named";
  event: string;
}

export interface SignalRTrigger {
  kind: "signalr";
  hubUrl: string;
  method: string;
}

export type ReactionGraph =
  | SequenceReaction
  | ParallelReaction
  | BranchReaction
  | SetReaction
  | CallReaction
  | RequestReaction
  | DispatchReaction
  | InjectReaction
  | ShowValidationErrorsReaction;

export interface SequenceReaction {
  kind: "sequence";
  steps: ReactionGraph[];
}

export interface ParallelReaction {
  kind: "parallel";
  steps: ReactionGraph[];
  completion: ParallelCompletion;
}

export type ParallelCompletion =
  | NoParallelCompletion
  | SettledParallelCompletion;

export interface NoParallelCompletion {
  kind: "none";
}

export interface SettledParallelCompletion {
  kind: "on-settled";
  reaction: ReactionGraph;
}

export interface BranchReaction {
  kind: "branch";
  cases: BranchCase[];
}

export interface BranchCase {
  guard: BranchGuard;
  reaction: ReactionGraph;
}

export type BranchGuard =
  | DefaultBranchGuard
  | ConditionalBranchGuard;

export interface DefaultBranchGuard {
  kind: "default";
}

export interface ConditionalBranchGuard {
  kind: "when";
  condition: ConditionGraph;
}

export interface SetReaction {
  kind: "set";
  on: SetTargetSource;
  property: string;
  value: ValueExpression;
}

export interface CallReaction {
  kind: "call";
  on: CallTargetSource;
  method: string;
  args: ValueExpression[];
}

export interface RequestReaction {
  kind: "request";
  request: RequestPlan;
}

export interface DispatchReaction {
  kind: "dispatch";
  event: string;
  payload: DispatchPayload;
}

export type DispatchPayload =
  | NoDispatchPayload
  | PresentDispatchPayload;

export interface NoDispatchPayload {
  kind: "none";
}

export interface PresentDispatchPayload {
  kind: "value";
  data: ValueExpression;
}

export interface InjectReaction {
  kind: "inject";
  slot: string;
  value: ValueExpression;
}

export interface ShowValidationErrorsReaction {
  kind: "show-validation-errors";
  container: string;
}

export type HttpMethod =
  | "GET"
  | "POST"
  | "PUT"
  | "DELETE";

export interface RequestPlan {
  method: HttpMethod;
  url: string;
  validation: RequestValidationTarget;
  input: RequestInput;
  whileLoading: ReactionGraph[];
  success: ResponseRoute[];
  error: ResponseRoute[];
  finally: ReactionGraph[];
  chain: RequestChain;
}

export type RequestValidationTarget =
  | NoRequestValidationTarget
  | ContainerRequestValidationTarget;

export interface NoRequestValidationTarget {
  kind: "none";
}

export interface ContainerRequestValidationTarget {
  kind: "container";
  container: string;
}

export type RequestChain =
  | TerminalRequestChain
  | FollowUpRequestChain;

export interface TerminalRequestChain {
  kind: "terminal";
}

export interface FollowUpRequestChain {
  kind: "follow-up";
  next: RequestPlan;
}

export type RequestInput =
  | NoRequestInput
  | GatherRequestInput;

export type RequestBodyFormat =
  | "json"
  | "form-data";

export interface NoRequestInput {
  kind: "none";
}

export interface GatherRequestInput {
  kind: "gather";
  assignments: RequestInputAssignment[];
  bodyFormat: RequestBodyFormat;
  registeredInputs: RegisteredInputSelection;
}

export type RegisteredInputSelection =
  | ExplicitRegisteredInputSelection
  | AllRegisteredInputsSelection;

export interface ExplicitRegisteredInputSelection {
  kind: "explicit";
}

export interface AllRegisteredInputsSelection {
  kind: "all-registered-inputs";
}

export interface RequestInputAssignment {
  target: RequestInputTarget;
  source: ValueExpression;
}

export type RequestInputTarget =
  | RequestPayloadTarget
  | RequestHeaderTarget
  | RequestRouteParameterTarget;

export interface RequestPayloadTarget {
  kind: "payload";
  name: string;
  path: StructuredPath;
}

export interface RequestHeaderTarget {
  kind: "header";
  name: string;
}

export interface RequestRouteParameterTarget {
  kind: "route-param";
  name: string;
}

export interface ResponseRoute {
  match: ResponseStatusMatch;
  reaction: ReactionGraph;
}

export type ResponseStatusMatch =
  | AnyResponseStatusMatch
  | ExactResponseStatusMatch;

export interface AnyResponseStatusMatch {
  kind: "any";
}

export interface ExactResponseStatusMatch {
  kind: "status";
  status: number;
}

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export type ValueExpression =
  | LiteralExpression
  | ReadExpression
  | ObjectExpression
  | ArrayExpression
  | ArrayOperationExpression;

export type ReadExpression =
  | ObjectPropertyReadExpression
  | ObjectMethodReadExpression
  | UrlParameterReadExpression
  | PayloadPathReadExpression
  | WholePayloadReadExpression
  | WholeElementReadExpression
  | DomPropertyReadExpression
  | ElementMethodReadExpression;

export interface LiteralExpression {
  kind: "literal";
  value: JsonValue;
  shape: Shape;
}

export interface NumericLiteralExpression {
  kind: "literal";
  value: number;
  shape: Shape;
}

export interface TextLiteralExpression {
  kind: "literal";
  value: string;
  shape: Shape;
}

export interface RangeLiteralExpression {
  kind: "literal";
  value: [JsonValue, JsonValue];
  shape: Shape;
}

export interface ObjectPropertyReadExpression {
  kind: "read";
  from: RuntimeObjectSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface ObjectMethodReadExpression {
  kind: "read";
  from: RuntimeObjectSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: MethodValueReadAccess;
}

export interface UrlParameterReadExpression {
  kind: "read";
  from: UrlSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface PayloadPathReadExpression {
  kind: "read";
  from: PayloadSource;
  member: string;
  path: StructuredPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface WholePayloadReadExpression {
  kind: "read";
  from: PayloadSource;
  member: "responseBody";
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface WholeElementReadExpression {
  kind: "read";
  from: PayloadSource;
  member: "elementValue";
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface DomPropertyReadExpression {
  kind: "read";
  from: DomSource;
  member: string;
  path: StructuredPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface ElementMethodReadExpression {
  kind: "read";
  from: PayloadSource;
  member: string;
  path: StructuredPath;
  shape: Shape;
  access: MethodValueReadAccess;
}

export type ValueReadAccess =
  | PropertyValueReadAccess
  | MethodValueReadAccess;

export interface PropertyValueReadAccess {
  kind: "property";
}

export interface MethodValueReadAccess {
  kind: "method";
  args: ValueExpression[];
}

export interface ObjectExpression {
  kind: "object";
  fields: Record<string, ValueExpression>;
  shape: Shape;
}

export interface ArrayExpression {
  kind: "array";
  items: ValueExpression[];
  shape: Shape;
}

export type ArrayOp =
  | "count"
  | "filter"
  | "map"
  | "sum"
  | "any"
  | "all"
  | "find"
  | "orderBy"
  | "orderByDescending";

export interface ArrayOperationExpression {
  kind: "array-op";
  op: ArrayOp;
  source: ValueExpression;
  predicate?: ValidationCondition;
  projection?: ValueExpression;
  itemShape: Shape;
  shape: Shape;
}

export type ValidationCondition =
  | CompareCondition
  | ValidationAllCondition
  | ValidationAnyCondition
  | ValidationNotCondition;

export interface ValidationAllCondition {
  kind: "all";
  terms: ValidationCondition[];
}

export interface ValidationAnyCondition {
  kind: "any";
  terms: ValidationCondition[];
}

export interface ValidationNotCondition {
  kind: "not";
  term: ValidationCondition;
}

export type ConditionGraph =
  | CompareCondition
  | AllCondition
  | AnyCondition
  | NotCondition
  | ConfirmCondition;

export type CompareOp =
  | "eq"
  | "neq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "truthy"
  | "falsy"
  | "is-null"
  | "not-null"
  | "is-empty"
  | "not-empty"
  | "in"
  | "not-in"
  | "between"
  | "contains"
  | "starts-with"
  | "ends-with"
  | "matches"
  | "min-length"
  | "array-contains";

export type CompareCondition =
  | UnaryCompareCondition
  | EqualityCompareCondition
  | OrderedCompareCondition
  | MembershipCompareCondition
  | RangeCompareCondition
  | TextCompareCondition
  | RegexCompareCondition
  | TextLengthCompareCondition
  | CollectionItemCompareCondition;

export type UnaryCompareOp =
  | "truthy"
  | "falsy"
  | "is-null"
  | "not-null"
  | "is-empty"
  | "not-empty";

export type EqualityCompareOp =
  | "eq"
  | "neq";

export type OrderedCompareOp =
  | "gt"
  | "gte"
  | "lt"
  | "lte";

export type MembershipCompareOp =
  | "in"
  | "not-in";

export type RangeCompareOp =
  | "between";

export type TextCompareOp =
  | "contains"
  | "starts-with"
  | "ends-with";

export type RegexCompareOp =
  | "matches";

export type TextLengthCompareOp =
  | "min-length";

export type CollectionItemCompareOp =
  | "array-contains";

export interface UnaryCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: UnaryCompareOp;
  right: NoComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface EqualityCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: EqualityCompareOp;
  right: PresentComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface OrderedCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: OrderedCompareOp;
  right: PresentComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface MembershipCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: MembershipCompareOp;
  right: CollectionComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface RangeCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: RangeCompareOp;
  right: RangeComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface TextCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: TextCompareOp;
  right: TextComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface RegexCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: RegexCompareOp;
  right: TextComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface TextLengthCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: TextLengthCompareOp;
  right: NumericComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface CollectionItemCompareCondition {
  kind: "compare";
  left: ValueExpression;
  op: CollectionItemCompareOp;
  right: LiteralComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export type ComparisonRightOperand =
  | NoComparisonRightOperand
  | PresentComparisonRightOperand
  | CollectionComparisonRightOperand
  | RangeComparisonRightOperand
  | TextComparisonRightOperand
  | NumericComparisonRightOperand
  | LiteralComparisonRightOperand;

export interface NoComparisonRightOperand {
  kind: "none";
}

export interface PresentComparisonRightOperand {
  kind: "value";
  value: ValueExpression;
}

export interface CollectionComparisonRightOperand {
  kind: "value";
  value: ArrayExpression;
}

export type RangeComparisonExpression = ArrayExpression & { items: [ValueExpression, ValueExpression] };

export interface RangeComparisonRightOperand {
  kind: "value";
  value: RangeComparisonExpression;
}

export interface TextComparisonRightOperand {
  kind: "value";
  value: TextLiteralExpression;
}

export interface NumericComparisonRightOperand {
  kind: "value";
  value: NumericLiteralExpression;
}

export interface LiteralComparisonRightOperand {
  kind: "value";
  value: LiteralExpression;
}

export interface AllCondition {
  kind: "all";
  terms: ConditionGraph[];
}

export interface AnyCondition {
  kind: "any";
  terms: ConditionGraph[];
}

export interface NotCondition {
  kind: "not";
  term: ConditionGraph;
}

export interface ConfirmCondition {
  kind: "confirm";
  message: string;
}

export type Shape =
  | StringShape
  | NumberShape
  | BooleanShape
  | DateShape
  | RawShape
  | ArrayShape
  | ObjectShape
  | NullableShape
  | AnyShape
  | NoneShape;

export interface StringShape {
  kind: "string";
}

export interface NumberShape {
  kind: "number";
}

export interface BooleanShape {
  kind: "boolean";
}

export interface DateShape {
  kind: "date";
}

export interface RawShape {
  kind: "raw";
}

export interface ArrayShape {
  kind: "array";
  item: Shape;
}

export interface ObjectShape {
  kind: "object";
  fields: Record<string, Shape>;
  additional: boolean;
}

export interface NullableShape {
  kind: "nullable";
  inner: Shape;
}

export interface AnyShape {
  kind: "any";
}

export interface NoneShape {
  kind: "none";
}

export type Path = PathSegment[];

export type EmptyPath = [];

export type StructuredPath = [PathSegment, ...PathSegment[]];

export type PathSegment =
  | PropertySegment
  | IndexSegment;

export interface PropertySegment {
  kind: "property";
  name: string;
}

export interface IndexSegment {
  kind: "index";
  index: number;
}
