// <auto-generated />
// Generated by Alis.Reactive.PlanModel.PlanTypeScriptContract.
// Do not edit by hand. Run `npm run generate:plan-types -w Alis.Reactive.Assets`.

export interface Plan {
  version: 3;
  planId: string;
  scope: PlanScope;
  types: Record<string, BrowserObjectContract>;
  components: Record<string, ComponentObject>;
  behaviors: Behavior[];
}

export type PlanScope =
  | RootPlanScope
  | PartialPlanScope;

export interface RootPlanScope {
  kind: "root";
}

export interface PartialPlanScope {
  kind: "partial";
}

export interface BrowserObjectContract {
  properties: Record<string, Property>;
  methods: Record<string, Method>;
  events: Record<string, Event>;
}

export interface Property {
  path: Path;
  shape: Shape;
  access: MemberAccess;
}

export type MemberAccess =
  | "read"
  | "write"
  | "readwrite";

export interface Method {
  path: Path;
  arguments: MethodArgumentContract;
  returns: Shape;
}

export type MethodArgumentContract =
  | OpenMethodArgumentContract
  | ExactMethodArgumentContract;

export interface OpenMethodArgumentContract {
  kind: "open";
}

export interface ExactMethodArgumentContract {
  kind: "exact";
  shapes: Shape[];
}

export type PayloadContract =
  | UntypedPayloadContract
  | TypedPayloadContract;

export interface UntypedPayloadContract {
  kind: "untyped";
}

export interface TypedPayloadContract {
  kind: "typed";
  type: string;
}

export interface Event {
  channel: string;
  payloadType: PayloadContract;
}

export type Vendor = string;

export type ComponentObject =
  | ObjectTargetComponent
  | OwnedDefinitionComponent
  | ValidationContainerComponentDefinition
  | LayoutObjectComponent;

export interface ObjectTargetComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: ObjectTargetComponentContribution;
  binding: NoInputBinding;
  container: NoValidationContainer;
}

export interface OwnedDefinitionComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: OwnedDefinitionComponentContribution;
  binding: RegisteredInputBinding;
  container: NoValidationContainer;
}

export interface ValidationContainerComponentDefinition {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: ValidationContainerComponentContribution;
  binding: InputBinding;
  container: ValidationContainerScope;
}

export interface LayoutObjectComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: LayoutObjectComponentContribution;
  binding: NoInputBinding;
  container: NoValidationContainer;
}

export type ComponentRole =
  | ObjectTargetComponentContribution
  | OwnedDefinitionComponentContribution
  | ValidationContainerComponentContribution
  | LayoutObjectComponentContribution;

export interface ObjectTargetComponentContribution {
  kind: "object-target";
}

export interface OwnedDefinitionComponentContribution {
  kind: "owned-definition";
}

export interface ValidationContainerComponentContribution {
  kind: "validation-container";
}

export interface LayoutObjectComponentContribution {
  kind: "layout-object";
}

export type InputBinding =
  | NoInputBinding
  | RegisteredInputBinding;

export interface NoInputBinding {
  kind: "none";
}

export interface RegisteredInputBinding {
  kind: "registered-input";
  bindingPath: string;
  path: StructuredPath;
  valueMember: string;
}

export type ValidationContainerBinding =
  | NoValidationContainer
  | ValidationContainerScope;

export interface NoValidationContainer {
  kind: "none";
}

export interface ValidationContainerScope {
  kind: "validation-container";
  validationRules: ComponentValidation[];
}

export interface ComponentValidation {
  component: string;
  value: ValueProducer;
  serverFieldName: string;
  rules: ValidationRule[];
}

export type ValidationRuleName =
  | "required"
  | "empty"
  | "minLength"
  | "maxLength"
  | "email"
  | "regex"
  | "url"
  | "creditCard"
  | "range"
  | "exclusiveRange"
  | "min"
  | "max"
  | "gt"
  | "lt"
  | "equalTo"
  | "notEqual"
  | "notEqualTo"
  | "atLeastOne";

export type ValidationRule =
  | NoOperandValidationRule
  | LengthValidationRule
  | RegexValidationRule
  | RangeValidationRule
  | OrderedComparisonValidationRule
  | PeerOrderedComparisonValidationRule
  | LiteralEqualityValidationRule
  | PeerEqualityValidationRule;

export type NoOperandValidationRuleName =
  | "required"
  | "empty"
  | "email"
  | "url"
  | "creditCard"
  | "atLeastOne";

export type LengthValidationRuleName =
  | "minLength"
  | "maxLength";

export type RegexValidationRuleName =
  | "regex";

export type RangeValidationRuleName =
  | "range"
  | "exclusiveRange";

export type OrderedComparisonValidationRuleName =
  | "min"
  | "max"
  | "gt"
  | "lt";

export type PeerOrderedComparisonValidationRuleName =
  | "min"
  | "max"
  | "gt"
  | "lt";

export type LiteralEqualityValidationRuleName =
  | "equalTo"
  | "notEqual";

export type PeerEqualityValidationRuleName =
  | "equalTo"
  | "notEqualTo";

export interface NoOperandValidationRule {
  name: NoOperandValidationRuleName;
  message: string;
  execution: NoOperandValidationRuleExecution;
}

export interface LengthValidationRule {
  name: LengthValidationRuleName;
  message: string;
  execution: NumericConstraintValidationRuleExecution;
}

export interface RegexValidationRule {
  name: RegexValidationRuleName;
  message: string;
  execution: TextConstraintValidationRuleExecution;
}

export interface RangeValidationRule {
  name: RangeValidationRuleName;
  message: string;
  execution: RangeConstraintValidationRuleExecution;
}

export interface OrderedComparisonValidationRule {
  name: OrderedComparisonValidationRuleName;
  message: string;
  execution: ScalarConstraintValidationRuleExecution;
}

export interface PeerOrderedComparisonValidationRule {
  name: PeerOrderedComparisonValidationRuleName;
  message: string;
  execution: PeerValidationRuleExecution;
}

export interface LiteralEqualityValidationRule {
  name: LiteralEqualityValidationRuleName;
  message: string;
  execution: ScalarConstraintValidationRuleExecution;
}

export interface PeerEqualityValidationRule {
  name: PeerEqualityValidationRuleName;
  message: string;
  execution: PeerValidationRuleExecution;
}

export type ValidationRuleExecution =
  | NoOperandValidationRuleExecution
  | ScalarConstraintValidationRuleExecution
  | NumericConstraintValidationRuleExecution
  | TextConstraintValidationRuleExecution
  | RangeConstraintValidationRuleExecution
  | PeerValidationRuleExecution;

export interface NoOperandValidationRuleExecution {
  target: "none";
  constraint: NoValidationRuleOperand;
  otherValue: NoValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface ScalarConstraintValidationRuleExecution {
  target: "constraint";
  constraint: ScalarValidationConstraintOperand;
  otherValue: NoValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface NumericConstraintValidationRuleExecution {
  target: "constraint";
  constraint: NumericValidationConstraintOperand;
  otherValue: NoValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface TextConstraintValidationRuleExecution {
  target: "constraint";
  constraint: TextValidationConstraintOperand;
  otherValue: NoValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface RangeConstraintValidationRuleExecution {
  target: "constraint";
  constraint: RangeValidationConstraintOperand;
  otherValue: NoValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export interface PeerValidationRuleExecution {
  target: "peer";
  constraint: NoValidationRuleOperand;
  otherValue: PeerValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export type ValidationRuleOperand =
  | NoValidationRuleOperand
  | ScalarValidationConstraintOperand
  | NumericValidationConstraintOperand
  | TextValidationConstraintOperand
  | RangeValidationConstraintOperand
  | PeerValidationRuleOperand;

export type ValidationConstraintOperand =
  | NoValidationRuleOperand
  | ScalarValidationConstraintOperand
  | NumericValidationConstraintOperand
  | TextValidationConstraintOperand
  | RangeValidationConstraintOperand;

export type ValidationPeerOperand =
  | NoValidationRuleOperand
  | PeerValidationRuleOperand;

export interface NoValidationRuleOperand {
  kind: "none";
}

export type LiteralValidationConstraintOperand =
  | ScalarValidationConstraintOperand
  | NumericValidationConstraintOperand
  | TextValidationConstraintOperand
  | RangeValidationConstraintOperand;

export interface ScalarValidationConstraintOperand {
  kind: "value";
  value: LiteralProducer;
}

export interface NumericValidationConstraintOperand {
  kind: "value";
  value: NumericLiteralProducer;
}

export interface TextValidationConstraintOperand {
  kind: "value";
  value: TextLiteralProducer;
}

export interface RangeValidationConstraintOperand {
  kind: "value";
  value: RangeLiteralProducer;
}

export interface PeerValidationRuleOperand {
  kind: "value";
  value: ReadProducer;
}

export type ValidationRuleActivation =
  | AlwaysValidationRuleActivation
  | ConditionalValidationRuleActivation;

export interface AlwaysValidationRuleActivation {
  kind: "always";
}

export interface ConditionalValidationRuleActivation {
  kind: "when";
  condition: ValidationCondition;
}

export type Source =
  | ComponentSource
  | PayloadSource
  | UrlSource
  | PluginSource;

export type RuntimeObjectSource =
  | ComponentSource
  | PluginSource;

export type SetTargetSource =
  | ComponentSource
  | PayloadSource;

export type CallTargetSource =
  | ComponentSource
  | PayloadSource
  | PluginSource;

export interface ComponentSource {
  kind: "component";
  component: string;
}

export interface UrlSource {
  kind: "url";
}

export interface PluginSource {
  kind: "plugin";
  name: string;
  type: string;
}

export type PayloadScope =
  | "event"
  | "success"
  | "error"
  | "request"
  | "dispatch"
  | "local";

export interface PayloadSource {
  kind: "payload";
  scope: PayloadScope;
  type: PayloadContract;
}

export interface Behavior {
  startsWhen: StartsWhen;
  reaction: Reaction;
}

export type StartsWhen =
  | PageReadyTrigger
  | DocumentEventTrigger
  | ComponentEventTrigger
  | ServerPushTrigger
  | SignalRTrigger;

export interface PageReadyTrigger {
  kind: "page-ready";
}

export interface DocumentEventTrigger {
  kind: "document-event";
  event: string;
  payloadType: PayloadContract;
}

export interface ComponentEventTrigger {
  kind: "component-event";
  component: string;
  event: string;
}

export interface ServerPushTrigger {
  kind: "server-push";
  url: string;
  eventFilter: ServerPushEventFilter;
}

export type ServerPushEventFilter =
  | AnyServerPushEventFilter
  | NamedServerPushEventFilter;

export interface AnyServerPushEventFilter {
  kind: "any";
  payloadType: PayloadContract;
}

export interface NamedServerPushEventFilter {
  kind: "named";
  event: string;
  payloadType: PayloadContract;
}

export interface SignalRTrigger {
  kind: "signalr";
  hubUrl: string;
  method: string;
  payloadType: PayloadContract;
}

export type Reaction =
  | SequenceReaction
  | ParallelReaction
  | BranchReaction
  | SetReaction
  | CallReaction
  | RequestReaction
  | DispatchReaction
  | InjectReaction
  | ShowValidationErrorsReaction;

export interface SequenceReaction {
  kind: "sequence";
  steps: Reaction[];
}

export interface ParallelReaction {
  kind: "parallel";
  steps: Reaction[];
  completion: ParallelCompletion;
}

export type ParallelCompletion =
  | NoParallelCompletion
  | SettledParallelCompletion;

export interface NoParallelCompletion {
  kind: "none";
}

export interface SettledParallelCompletion {
  kind: "on-settled";
  reaction: Reaction;
}

export interface BranchReaction {
  kind: "branch";
  cases: BranchCase[];
}

export interface BranchCase {
  guard: BranchGuard;
  reaction: Reaction;
}

export type BranchGuard =
  | DefaultBranchGuard
  | ConditionalBranchGuard;

export interface DefaultBranchGuard {
  kind: "default";
}

export interface ConditionalBranchGuard {
  kind: "when";
  condition: Condition;
}

export interface SetReaction {
  kind: "set";
  on: SetTargetSource;
  property: string;
  value: ValueProducer;
}

export interface CallReaction {
  kind: "call";
  on: CallTargetSource;
  method: string;
  args: ValueProducer[];
}

export interface RequestReaction {
  kind: "request";
  request: Request;
}

export interface DispatchReaction {
  kind: "dispatch";
  event: string;
  payload: DispatchPayload;
}

export type DispatchPayload =
  | NoDispatchPayload
  | PresentDispatchPayload;

export interface NoDispatchPayload {
  kind: "none";
}

export interface PresentDispatchPayload {
  kind: "value";
  data: ValueProducer;
  payloadType: PayloadContract;
}

export interface InjectReaction {
  kind: "inject";
  target: InjectionTarget;
  value: ValueProducer;
}

export type InjectionTarget =
  | PartialSlotInjectionTarget;

export interface PartialSlotInjectionTarget {
  kind: "partial-slot";
  component: string;
}

export interface ShowValidationErrorsReaction {
  kind: "show-validation-errors";
  container: string;
}

export type HttpMethod =
  | "GET"
  | "POST"
  | "PUT"
  | "DELETE"
  | "PATCH";

export interface Request {
  method: HttpMethod;
  url: string;
  headers: Record<string, ValueProducer>;
  routeParams: Record<string, ValueProducer>;
  validation: RequestValidationTarget;
  input: RequestInput;
  before: Reaction[];
  success: ResponseHandler[];
  error: ResponseHandler[];
  complete: Reaction[];
  chain: RequestChain;
}

export type RequestValidationTarget =
  | NoRequestValidationTarget
  | ContainerRequestValidationTarget;

export interface NoRequestValidationTarget {
  kind: "none";
}

export interface ContainerRequestValidationTarget {
  kind: "container";
  container: string;
}

export type RequestChain =
  | TerminalRequestChain
  | FollowUpRequestChain;

export interface TerminalRequestChain {
  kind: "terminal";
}

export interface FollowUpRequestChain {
  kind: "follow-up";
  next: Request;
}

export type RequestInput =
  | NoRequestInput
  | GatherInput;

export type RequestBodyFormat =
  | "json"
  | "form-data";

export interface NoRequestInput {
  kind: "none";
}

export interface GatherInput {
  kind: "gather";
  payloadAssignments: RequestPayloadAssignment[];
  bodyFormat: RequestBodyFormat;
  sourceSelection: GatherSourceSelection;
}

export type GatherSourceSelection =
  | ExplicitGatherSourceSelection
  | AllRegisteredInputsGatherSourceSelection;

export interface ExplicitGatherSourceSelection {
  kind: "explicit";
}

export interface AllRegisteredInputsGatherSourceSelection {
  kind: "all-registered-inputs";
}

export interface RequestPayloadAssignment {
  target: RequestPayloadTarget;
  source: ValueProducer;
}

export interface RequestPayloadTarget {
  name: string;
  path: StructuredPath;
}

export interface ResponseHandler {
  match: ResponseStatusMatch;
  reaction: Reaction;
}

export type ResponseStatusMatch =
  | AnyResponseStatusMatch
  | ExactResponseStatusMatch;

export interface AnyResponseStatusMatch {
  kind: "any";
}

export interface ExactResponseStatusMatch {
  kind: "status";
  status: number;
}

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export type ValueProducer =
  | LiteralProducer
  | ReadProducer
  | ObjectProducer
  | ArrayProducer;

export type ReadProducer =
  | ObjectPropertyReadProducer
  | ObjectMethodReadProducer
  | UrlParameterReadProducer
  | PayloadPathReadProducer
  | WholePayloadReadProducer;

export interface LiteralProducer {
  kind: "literal";
  value: JsonValue;
  shape: Shape;
}

export interface NumericLiteralProducer {
  kind: "literal";
  value: number;
  shape: Shape;
}

export interface TextLiteralProducer {
  kind: "literal";
  value: string;
  shape: Shape;
}

export interface RangeLiteralProducer {
  kind: "literal";
  value: [JsonValue, JsonValue];
  shape: Shape;
}

export interface ObjectPropertyReadProducer {
  kind: "read";
  from: RuntimeObjectSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface ObjectMethodReadProducer {
  kind: "read";
  from: RuntimeObjectSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: MethodValueReadAccess;
}

export interface UrlParameterReadProducer {
  kind: "read";
  from: UrlSource;
  member: string;
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface PayloadPathReadProducer {
  kind: "read";
  from: PayloadSource;
  member: string;
  path: StructuredPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export interface WholePayloadReadProducer {
  kind: "read";
  from: PayloadSource;
  member: "responseBody";
  path: EmptyPath;
  shape: Shape;
  access: PropertyValueReadAccess;
}

export type ValueReadAccess =
  | PropertyValueReadAccess
  | MethodValueReadAccess;

export interface PropertyValueReadAccess {
  kind: "property";
}

export interface MethodValueReadAccess {
  kind: "method";
  args: ValueProducer[];
}

export interface ObjectProducer {
  kind: "object";
  fields: Record<string, ValueProducer>;
  shape: Shape;
}

export interface ArrayProducer {
  kind: "array";
  items: ValueProducer[];
  shape: Shape;
}

export type ValidationCondition =
  | CompareCondition
  | ValidationAllCondition
  | ValidationAnyCondition
  | ValidationNotCondition;

export interface ValidationAllCondition {
  kind: "all";
  terms: ValidationCondition[];
}

export interface ValidationAnyCondition {
  kind: "any";
  terms: ValidationCondition[];
}

export interface ValidationNotCondition {
  kind: "not";
  term: ValidationCondition;
}

export type Condition =
  | CompareCondition
  | AllCondition
  | AnyCondition
  | NotCondition
  | ConfirmCondition;

export type CompareOp =
  | "eq"
  | "neq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "truthy"
  | "falsy"
  | "is-null"
  | "not-null"
  | "is-empty"
  | "not-empty"
  | "in"
  | "not-in"
  | "between"
  | "contains"
  | "starts-with"
  | "ends-with"
  | "matches"
  | "min-length"
  | "array-contains";

export type CompareCondition =
  | UnaryCompareCondition
  | EqualityCompareCondition
  | OrderedCompareCondition
  | MembershipCompareCondition
  | RangeCompareCondition
  | TextCompareCondition
  | RegexCompareCondition
  | TextLengthCompareCondition
  | CollectionItemCompareCondition;

export type UnaryCompareOp =
  | "truthy"
  | "falsy"
  | "is-null"
  | "not-null"
  | "is-empty"
  | "not-empty";

export type EqualityCompareOp =
  | "eq"
  | "neq";

export type OrderedCompareOp =
  | "gt"
  | "gte"
  | "lt"
  | "lte";

export type MembershipCompareOp =
  | "in"
  | "not-in";

export type RangeCompareOp =
  | "between";

export type TextCompareOp =
  | "contains"
  | "starts-with"
  | "ends-with";

export type RegexCompareOp =
  | "matches";

export type TextLengthCompareOp =
  | "min-length";

export type CollectionItemCompareOp =
  | "array-contains";

export interface UnaryCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: UnaryCompareOp;
  right: NoComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface EqualityCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: EqualityCompareOp;
  right: PresentComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface OrderedCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: OrderedCompareOp;
  right: PresentComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface MembershipCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: MembershipCompareOp;
  right: CollectionComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface RangeCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: RangeCompareOp;
  right: RangeComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface TextCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: TextCompareOp;
  right: TextComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface RegexCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: RegexCompareOp;
  right: TextComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface TextLengthCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: TextLengthCompareOp;
  right: NumericComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export interface CollectionItemCompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: CollectionItemCompareOp;
  right: LiteralComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export type ComparisonRightOperand =
  | NoComparisonRightOperand
  | PresentComparisonRightOperand
  | CollectionComparisonRightOperand
  | RangeComparisonRightOperand
  | TextComparisonRightOperand
  | NumericComparisonRightOperand
  | LiteralComparisonRightOperand;

export interface NoComparisonRightOperand {
  kind: "none";
}

export interface PresentComparisonRightOperand {
  kind: "value";
  value: ValueProducer;
}

export interface CollectionComparisonRightOperand {
  kind: "value";
  value: ArrayProducer;
}

export type RangeComparisonProducer = ArrayProducer & { items: [ValueProducer, ValueProducer] };

export interface RangeComparisonRightOperand {
  kind: "value";
  value: RangeComparisonProducer;
}

export interface TextComparisonRightOperand {
  kind: "value";
  value: TextLiteralProducer;
}

export interface NumericComparisonRightOperand {
  kind: "value";
  value: NumericLiteralProducer;
}

export interface LiteralComparisonRightOperand {
  kind: "value";
  value: LiteralProducer;
}

export interface AllCondition {
  kind: "all";
  terms: Condition[];
}

export interface AnyCondition {
  kind: "any";
  terms: Condition[];
}

export interface NotCondition {
  kind: "not";
  term: Condition;
}

export interface ConfirmCondition {
  kind: "confirm";
  message: string;
}

export type Shape =
  | StringShape
  | NumberShape
  | BooleanShape
  | DateShape
  | RawShape
  | ArrayShape
  | ObjectShape
  | NullableShape
  | AnyShape
  | NoneShape;

export interface StringShape {
  kind: "string";
}

export interface NumberShape {
  kind: "number";
}

export interface BooleanShape {
  kind: "boolean";
}

export interface DateShape {
  kind: "date";
}

export interface RawShape {
  kind: "raw";
}

export interface ArrayShape {
  kind: "array";
  item: Shape;
}

export interface ObjectShape {
  kind: "object";
  fields: Record<string, Shape>;
  additional: boolean;
}

export interface NullableShape {
  kind: "nullable";
  inner: Shape;
}

export interface AnyShape {
  kind: "any";
}

export interface NoneShape {
  kind: "none";
}

export type Path = PathSegment[];

export type EmptyPath = [];

export type StructuredPath = [PathSegment, ...PathSegment[]];

export type PathSegment =
  | PropertySegment
  | IndexSegment;

export interface PropertySegment {
  kind: "property";
  name: string;
}

export interface IndexSegment {
  kind: "index";
  index: number;
}
