// <auto-generated />
// Generated by Alis.Reactive.PlanModel.PlanTypeScriptContract.
// Do not edit by hand. Run `npm run generate:plan-types -w Alis.Reactive.Assets`.

export interface Plan {
  version: 3;
  planId: string;
  scope: PlanScope;
  types: Record<string, JsType>;
  components: Record<string, Component>;
  behaviors: Behavior[];
}

export type PlanScope =
  | RootPlanScope
  | PartialPlanScope;

export interface RootPlanScope {
  kind: "root";
}

export interface PartialPlanScope {
  kind: "partial";
  partId: string;
}

export interface JsType {
  properties: Record<string, Property>;
  methods: Record<string, Method>;
  events: Record<string, Event>;
}

export interface Property {
  path: Path;
  shape: Shape;
  access: MemberAccess;
}

export type MemberAccess =
  | "read"
  | "write"
  | "readwrite";

export interface Method {
  path: Path;
  arguments: MethodArgumentContract;
  returns: Shape;
}

export type MethodArgumentContract =
  | OpenMethodArgumentContract
  | ExactMethodArgumentContract;

export interface OpenMethodArgumentContract {
  kind: "open";
}

export interface ExactMethodArgumentContract {
  kind: "exact";
  shapes: Shape[];
}

export type PayloadContract =
  | UntypedPayloadContract
  | TypedPayloadContract;

export interface UntypedPayloadContract {
  kind: "untyped";
}

export interface TypedPayloadContract {
  kind: "typed";
  type: string;
}

export interface Event {
  channel: string;
  payloadType: PayloadContract;
}

export type Vendor = string;

export type Component =
  | ObjectTargetComponent
  | OwnedDefinitionComponent
  | ValidationContainerComponentDefinition
  | LayoutObjectComponent;

export interface ObjectTargetComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: ObjectTargetComponentContribution;
  binding: UnboundComponentBinding;
  container: UnscopedComponentContainer;
}

export interface OwnedDefinitionComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: OwnedDefinitionComponentContribution;
  binding: RegisteredInputBinding;
  container: UnscopedComponentContainer;
}

export interface ValidationContainerComponentDefinition {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: ValidationContainerComponentContribution;
  binding: ComponentBinding;
  container: ValidationContainerScope;
}

export interface LayoutObjectComponent {
  id: string;
  vendor: Vendor;
  type: string;
  contribution: LayoutObjectComponentContribution;
  binding: UnboundComponentBinding;
  container: UnscopedComponentContainer;
}

export type ComponentContributionIntent =
  | ObjectTargetComponentContribution
  | OwnedDefinitionComponentContribution
  | ValidationContainerComponentContribution
  | LayoutObjectComponentContribution;

export interface ObjectTargetComponentContribution {
  kind: "object-target";
}

export interface OwnedDefinitionComponentContribution {
  kind: "owned-definition";
}

export interface ValidationContainerComponentContribution {
  kind: "validation-container";
}

export interface LayoutObjectComponentContribution {
  kind: "layout-object";
}

export type ComponentBinding =
  | UnboundComponentBinding
  | RegisteredInputBinding;

export interface UnboundComponentBinding {
  kind: "none";
}

export interface RegisteredInputBinding {
  kind: "registered-input";
  bindingPath: string;
  valueMember: string;
}

export type ComponentContainer =
  | UnscopedComponentContainer
  | ValidationContainerScope;

export interface UnscopedComponentContainer {
  kind: "none";
}

export interface ValidationContainerScope {
  kind: "validation-container";
  components: string[];
  validationRules: ComponentValidation[];
}

export interface ComponentValidation {
  component: string;
  value: ValueProducer;
  serverFieldName: string;
  rules: ValidationRule[];
}

export type ValidationRuleName =
  | "required"
  | "empty"
  | "minLength"
  | "maxLength"
  | "email"
  | "regex"
  | "url"
  | "creditCard"
  | "range"
  | "exclusiveRange"
  | "min"
  | "max"
  | "gt"
  | "lt"
  | "equalTo"
  | "notEqual"
  | "notEqualTo"
  | "atLeastOne";

export interface ValidationRule {
  name: ValidationRuleName;
  message: string;
  execution: ValidationRuleExecution;
}

export interface ValidationRuleExecution {
  constraint: ValidationRuleOperand;
  otherValue: ValidationRuleOperand;
  activation: ValidationRuleActivation;
  comparisonShape: Shape;
}

export type ValidationRuleOperand =
  | NoValidationRuleOperand
  | ValueValidationRuleOperand;

export interface NoValidationRuleOperand {
  kind: "none";
}

export interface ValueValidationRuleOperand {
  kind: "value";
  value: ValueProducer;
}

export type ValidationRuleActivation =
  | AlwaysValidationRuleActivation
  | ConditionalValidationRuleActivation;

export interface AlwaysValidationRuleActivation {
  kind: "always";
}

export interface ConditionalValidationRuleActivation {
  kind: "when";
  condition: ValidationCondition;
}

export type Source =
  | ComponentSource
  | PayloadSource
  | UrlSource
  | PluginSource;

export interface ComponentSource {
  kind: "component";
  component: string;
}

export interface UrlSource {
  kind: "url";
}

export interface PluginSource {
  kind: "plugin";
  name: string;
  type: string;
}

export type PayloadScope =
  | "event"
  | "success"
  | "error"
  | "request"
  | "dispatch"
  | "local";

export interface PayloadSource {
  kind: "payload";
  scope: PayloadScope;
  type: PayloadContract;
}

export interface Behavior {
  startsWhen: StartsWhen;
  reaction: Reaction;
}

export type StartsWhen =
  | PageReadyTrigger
  | DocumentEventTrigger
  | ComponentEventTrigger
  | ServerPushTrigger
  | SignalRTrigger;

export interface PageReadyTrigger {
  kind: "page-ready";
}

export interface DocumentEventTrigger {
  kind: "document-event";
  event: string;
  payloadType: PayloadContract;
}

export interface ComponentEventTrigger {
  kind: "component-event";
  component: string;
  event: string;
}

export interface ServerPushTrigger {
  kind: "server-push";
  url: string;
  eventFilter: ServerPushEventFilter;
}

export type ServerPushEventFilter =
  | AnyServerPushEventFilter
  | NamedServerPushEventFilter;

export interface AnyServerPushEventFilter {
  kind: "any";
  payloadType: PayloadContract;
}

export interface NamedServerPushEventFilter {
  kind: "named";
  event: string;
  payloadType: PayloadContract;
}

export interface SignalRTrigger {
  kind: "signalr";
  hubUrl: string;
  method: string;
  payloadType: PayloadContract;
}

export type Reaction =
  | SequenceReaction
  | ParallelReaction
  | BranchReaction
  | SetReaction
  | CallReaction
  | RequestReaction
  | DispatchReaction
  | InjectReaction
  | ShowValidationErrorsReaction;

export interface SequenceReaction {
  kind: "sequence";
  steps: Reaction[];
}

export interface ParallelReaction {
  kind: "parallel";
  steps: Reaction[];
  completion: ParallelCompletion;
}

export type ParallelCompletion =
  | NoParallelCompletion
  | SettledParallelCompletion;

export interface NoParallelCompletion {
  kind: "none";
}

export interface SettledParallelCompletion {
  kind: "on-settled";
  reaction: Reaction;
}

export interface BranchReaction {
  kind: "branch";
  cases: BranchCase[];
}

export interface BranchCase {
  guard: BranchGuard;
  reaction: Reaction;
}

export type BranchGuard =
  | DefaultBranchGuard
  | ConditionalBranchGuard;

export interface DefaultBranchGuard {
  kind: "default";
}

export interface ConditionalBranchGuard {
  kind: "when";
  condition: Condition;
}

export interface SetReaction {
  kind: "set";
  on: Source;
  property: string;
  value: ValueProducer;
}

export interface CallReaction {
  kind: "call";
  on: Source;
  method: string;
  args: ValueProducer[];
}

export interface RequestReaction {
  kind: "request";
  request: Request;
}

export interface DispatchReaction {
  kind: "dispatch";
  event: string;
  payload: DispatchPayload;
}

export type DispatchPayload =
  | NoDispatchPayload
  | PresentDispatchPayload;

export interface NoDispatchPayload {
  kind: "none";
}

export interface PresentDispatchPayload {
  kind: "value";
  data: ValueProducer;
  payloadType: PayloadContract;
}

export interface InjectReaction {
  kind: "inject";
  target: InjectionTarget;
  value: ValueProducer;
}

export type InjectionTarget =
  | PartialSlotInjectionTarget;

export interface PartialSlotInjectionTarget {
  kind: "partial-slot";
  component: string;
}

export interface ShowValidationErrorsReaction {
  kind: "show-validation-errors";
  container: string;
}

export type HttpMethod =
  | "GET"
  | "POST"
  | "PUT"
  | "DELETE"
  | "PATCH";

export interface Request {
  method: HttpMethod;
  url: string;
  headers: Record<string, ValueProducer>;
  routeParams: Record<string, ValueProducer>;
  validation: RequestValidationTarget;
  input: RequestInput;
  before: Reaction[];
  success: ResponseHandler[];
  error: ResponseHandler[];
  complete: Reaction[];
  chain: RequestChain;
}

export type RequestValidationTarget =
  | NoRequestValidationTarget
  | ContainerRequestValidationTarget;

export interface NoRequestValidationTarget {
  kind: "none";
}

export interface ContainerRequestValidationTarget {
  kind: "container";
  container: string;
}

export type RequestChain =
  | TerminalRequestChain
  | FollowUpRequestChain;

export interface TerminalRequestChain {
  kind: "terminal";
}

export interface FollowUpRequestChain {
  kind: "follow-up";
  next: Request;
}

export type RequestInput =
  | NoRequestInput
  | GatherInput
  | ValueInput;

export type Transport =
  | "json"
  | "form-data";

export interface NoRequestInput {
  kind: "none";
}

export interface GatherInput {
  kind: "gather";
  declaredFields: GatherPayloadField[];
  registeredInputFields: GatherPayloadField[];
  transport: Transport;
  supplementalFields: SupplementalGatherFields;
  selection: GatherSelection;
}

export type SupplementalGatherFields =
  | NoSupplementalGatherFields
  | DeclaredSupplementalGatherFields;

export interface NoSupplementalGatherFields {
  kind: "none";
}

export interface DeclaredSupplementalGatherFields {
  kind: "declared";
  fields: GatherPayloadField[];
}

export type GatherSelection =
  | ExplicitGatherSelection
  | AllRegisteredInputsGatherSelection;

export interface ExplicitGatherSelection {
  kind: "explicit";
}

export interface AllRegisteredInputsGatherSelection {
  kind: "all-registered-inputs";
}

export interface ValueInput {
  kind: "value";
  value: ObjectProducer;
  transport: Transport;
}

export interface GatherPayloadField {
  payloadPath: string;
  value: ValueProducer;
}

export interface ResponseHandler {
  match: ResponseStatusMatch;
  reaction: Reaction;
}

export type ResponseStatusMatch =
  | AnyResponseStatusMatch
  | ExactResponseStatusMatch;

export interface AnyResponseStatusMatch {
  kind: "any";
}

export interface ExactResponseStatusMatch {
  kind: "status";
  status: number;
}

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export type ValueProducer =
  | LiteralProducer
  | ReadProducer
  | ObjectProducer
  | ArrayProducer;

export interface LiteralProducer {
  kind: "literal";
  value: JsonValue;
  shape: Shape;
}

export interface ReadProducer {
  kind: "read";
  from: Source;
  member: string;
  path: Path;
  shape: Shape;
  access: ValueReadAccess;
}

export type ValueReadAccess =
  | PropertyValueReadAccess
  | MethodValueReadAccess;

export interface PropertyValueReadAccess {
  kind: "property";
}

export interface MethodValueReadAccess {
  kind: "method";
  args: ValueProducer[];
}

export interface ObjectProducer {
  kind: "object";
  fields: Record<string, ValueProducer>;
  shape: Shape;
}

export interface ArrayProducer {
  kind: "array";
  items: ValueProducer[];
  shape: Shape;
}

export type ValidationCondition =
  | CompareCondition
  | ValidationAllCondition
  | ValidationAnyCondition
  | ValidationNotCondition;

export interface ValidationAllCondition {
  kind: "all";
  terms: ValidationCondition[];
}

export interface ValidationAnyCondition {
  kind: "any";
  terms: ValidationCondition[];
}

export interface ValidationNotCondition {
  kind: "not";
  term: ValidationCondition;
}

export type Condition =
  | CompareCondition
  | AllCondition
  | AnyCondition
  | NotCondition
  | ConfirmCondition;

export type CompareOp =
  | "eq"
  | "neq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "truthy"
  | "falsy"
  | "is-null"
  | "not-null"
  | "is-empty"
  | "not-empty"
  | "in"
  | "not-in"
  | "between"
  | "contains"
  | "starts-with"
  | "ends-with"
  | "matches"
  | "min-length"
  | "array-contains";

export interface CompareCondition {
  kind: "compare";
  left: ValueProducer;
  op: CompareOp;
  right: ComparisonRightOperand;
  shape: Shape;
  itemShape: Shape;
}

export type ComparisonRightOperand =
  | NoComparisonRightOperand
  | PresentComparisonRightOperand;

export interface NoComparisonRightOperand {
  kind: "none";
}

export interface PresentComparisonRightOperand {
  kind: "value";
  value: ValueProducer;
}

export interface AllCondition {
  kind: "all";
  terms: Condition[];
}

export interface AnyCondition {
  kind: "any";
  terms: Condition[];
}

export interface NotCondition {
  kind: "not";
  term: Condition;
}

export interface ConfirmCondition {
  kind: "confirm";
  message: string;
}

export type Shape =
  | StringShape
  | NumberShape
  | BooleanShape
  | DateShape
  | RawShape
  | ArrayShape
  | ObjectShape
  | NullableShape
  | AnyShape
  | NoneShape;

export interface StringShape {
  kind: "string";
}

export interface NumberShape {
  kind: "number";
}

export interface BooleanShape {
  kind: "boolean";
}

export interface DateShape {
  kind: "date";
}

export interface RawShape {
  kind: "raw";
}

export interface ArrayShape {
  kind: "array";
  item: Shape;
}

export interface ObjectShape {
  kind: "object";
  fields: Record<string, Shape>;
  additional: boolean;
}

export interface NullableShape {
  kind: "nullable";
  inner: Shape;
}

export interface AnyShape {
  kind: "any";
}

export interface NoneShape {
  kind: "none";
}

export type Path = PathSegment[];

export type PathSegment =
  | PropertySegment
  | IndexSegment;

export interface PropertySegment {
  kind: "property";
  name: string;
}

export interface IndexSegment {
  kind: "index";
  index: number;
}
