using System.Text;
using System.Xml.Linq;

// ── Configuration ──
var config = args.Length > 0 ? args[0] : "Debug";
var repoRoot = FindRepoRoot();
var xmlFiles = new[]
{
    Path.Combine(repoRoot, $"Alis.Reactive/bin/{config}/net10.0/Alis.Reactive.xml"),
    Path.Combine(repoRoot, $"Alis.Reactive.Native/bin/{config}/net10.0/Alis.Reactive.Native.xml"),
    Path.Combine(repoRoot, $"Alis.Reactive.Fusion/bin/{config}/net10.0/Alis.Reactive.Fusion.xml"),
};
var outputPath = Path.Combine(repoRoot, "docs-site/src/content/docs/reference/api-reference.md");

// ── Parse all XML files ──
var allMembers = new List<DocMember>();
foreach (var xmlFile in xmlFiles)
{
    if (!File.Exists(xmlFile))
    {
        Console.Error.WriteLine($"WARNING: XML file not found: {xmlFile}");
        Console.Error.WriteLine("Run 'dotnet build' first to generate XML documentation files.");
        continue;
    }

    var doc = XDocument.Load(xmlFile);
    var assemblyName = doc.Root?.Element("assembly")?.Element("name")?.Value ?? "Unknown";

    foreach (var member in doc.Descendants("member"))
    {
        var name = member.Attribute("name")?.Value;
        if (string.IsNullOrEmpty(name)) continue;

        allMembers.Add(new DocMember(name, assemblyName, member));
    }
}

if (allMembers.Count == 0)
{
    Console.Error.WriteLine("ERROR: No XML documentation members found. Run 'dotnet build' first.");
    return 1;
}

// ── Filter: skip internal constructors ──
var publicMembers = allMembers
    .Where(m => !IsInternal(m))
    .ToList();

// ── Group by namespace → type ──
var types = publicMembers
    .Where(m => m.Kind == MemberKind.Type)
    .OrderBy(m => m.Namespace)
    .ThenBy(m => m.TypeName)
    .ToList();

var membersByType = publicMembers
    .Where(m => m.Kind != MemberKind.Type)
    .GroupBy(m => m.FullTypeName)
    .ToDictionary(g => g.Key, g => g.OrderBy(m => m.MemberName).ToList());

// ── Generate markdown ──
var sb = new StringBuilder();
sb.AppendLine("---");
sb.AppendLine("title: API Reference");
sb.AppendLine("description: Complete public API — every method, every overload, every signature. Auto-generated from XML documentation.");
sb.AppendLine("sidebar:");
sb.AppendLine("  order: 0");
sb.AppendLine("---");
sb.AppendLine();
sb.AppendLine("<!-- AUTO-GENERATED by tools/ApiDocGenerator. Do not edit manually. -->");
sb.AppendLine("<!-- Run: npm run build:api-docs -->");
sb.AppendLine();
sb.AppendLine("Complete public API for Alis.Reactive. Auto-generated from XML documentation comments.");
sb.AppendLine("For usage and examples, see the [Grammar Tree](../../csharp-modules/mental-model/#the-grammar-tree) and the [Reactivity](../../csharp-modules/reactivity/triggers-and-reactions/) pages.");
sb.AppendLine();

// Group types by assembly for top-level sections
var byAssembly = types.GroupBy(t => t.Assembly).OrderBy(g => g.Key);
foreach (var assemblyGroup in byAssembly)
{
    var byNamespace = assemblyGroup.GroupBy(t => t.Namespace).OrderBy(g => g.Key);
    foreach (var nsGroup in byNamespace)
    {
        sb.AppendLine($"## {SimplifyNamespace(nsGroup.Key)}");
        sb.AppendLine();

        foreach (var type in nsGroup)
        {
            sb.AppendLine($"### {type.DisplayTypeName}");
            sb.AppendLine();

            var summary = GetSummaryText(type.Element);
            if (!string.IsNullOrWhiteSpace(summary))
            {
                sb.AppendLine(summary.Trim());
                sb.AppendLine();
            }

            if (membersByType.TryGetValue(type.FullTypeName, out var members))
            {
                var properties = members.Where(m => m.Kind == MemberKind.Property).ToList();
                var methods = members.Where(m => m.Kind == MemberKind.Method).ToList();

                if (properties.Count > 0)
                {
                    sb.AppendLine("```csharp");
                    sb.AppendLine("// Properties");
                    foreach (var prop in properties)
                    {
                        var propSummary = GetSummaryInline(prop.Element);
                        sb.AppendLine($"{prop.DisplaySignature}  // {propSummary}");
                    }
                    sb.AppendLine("```");
                    sb.AppendLine();
                }

                if (methods.Count > 0)
                {
                    sb.AppendLine("```csharp");
                    foreach (var method in methods)
                    {
                        sb.AppendLine(method.DisplaySignature);
                    }
                    sb.AppendLine("```");
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
    }
}

// ── Write output ──
var outputDir = Path.GetDirectoryName(outputPath)!;
Directory.CreateDirectory(outputDir);
File.WriteAllText(outputPath, sb.ToString());

Console.WriteLine($"Generated API reference: {outputPath}");
Console.WriteLine($"  Types: {types.Count}");
Console.WriteLine($"  Members: {publicMembers.Count - types.Count}");
Console.WriteLine($"  From: {xmlFiles.Length} XML files");

return 0;

// ══════════════════════════════════════════════════════
// Helper methods
// ══════════════════════════════════════════════════════

static string FindRepoRoot()
{
    var dir = Directory.GetCurrentDirectory();
    while (dir != null)
    {
        if (File.Exists(Path.Combine(dir, "package.json")) &&
            Directory.Exists(Path.Combine(dir, "Alis.Reactive")))
            return dir;
        dir = Directory.GetParent(dir)?.FullName;
    }
    return Directory.GetCurrentDirectory();
}

static bool IsInternal(DocMember m)
{
    var summary = m.Element.Element("summary")?.Value ?? "";
    if (summary.Contains("NEVER make public", StringComparison.OrdinalIgnoreCase))
        return true;
    if (m.Kind == MemberKind.Method && m.MemberName == "#ctor")
        return true;
    return false;
}

static string GetSummaryText(XElement member)
{
    var summary = member.Element("summary");
    if (summary == null) return "";
    return CleanXmlText(summary);
}

static string GetSummaryInline(XElement member)
{
    var summary = member.Element("summary");
    if (summary == null) return "";
    return CleanXmlText(summary).Trim().Replace("\n", " ");
}

static string CleanXmlText(XElement element)
{
    var sb = new StringBuilder();
    foreach (var node in element.Nodes())
    {
        if (node is XText text)
        {
            sb.Append(text.Value);
        }
        else if (node is XElement el)
        {
            switch (el.Name.LocalName)
            {
                case "c":
                    sb.Append($"`{el.Value}`");
                    break;
                case "code":
                    sb.AppendLine();
                    sb.AppendLine("```csharp");
                    sb.AppendLine(el.Value.Trim());
                    sb.AppendLine("```");
                    break;
                case "see":
                    var cref = el.Attribute("cref")?.Value;
                    var langword = el.Attribute("langword")?.Value;
                    if (langword != null)
                        sb.Append($"`{langword}`");
                    else if (cref != null)
                        sb.Append($"`{SimplifyCref(cref)}`");
                    else
                        sb.Append(el.Value);
                    break;
                case "para":
                    sb.AppendLine();
                    sb.Append(CleanXmlText(el));
                    break;
                case "paramref":
                    sb.Append($"`{el.Attribute("name")?.Value}`");
                    break;
                case "typeparamref":
                    sb.Append($"`{el.Attribute("name")?.Value}`");
                    break;
                case "b":
                    sb.Append($"**{el.Value}**");
                    break;
                default:
                    sb.Append(CleanXmlText(el));
                    break;
            }
        }
    }
    return sb.ToString();
}

static string SimplifyCref(string cref)
{
    if (cref.Length > 2 && cref[1] == ':')
        cref = cref[2..];
    var lastDot = cref.LastIndexOf('.');
    if (lastDot >= 0) cref = cref[(lastDot + 1)..];
    return CleanGenericNotation(cref);
}

static string SimplifyNamespace(string ns)
{
    return ns.Replace("Alis.Reactive.", "").Replace(".", " — ");
}

static string CleanGenericNotation(string name)
{
    var idx = name.IndexOf('`');
    if (idx >= 0) return $"{name[..idx]}<T>";
    return name;
}

// ══════════════════════════════════════════════════════
// Types
// ══════════════════════════════════════════════════════

enum MemberKind { Type, Method, Property, Field, Event }

record DocMember(string RawName, string Assembly, XElement Element)
{
    public MemberKind Kind => RawName[0] switch
    {
        'T' => MemberKind.Type,
        'M' => MemberKind.Method,
        'P' => MemberKind.Property,
        'F' => MemberKind.Field,
        'E' => MemberKind.Event,
        _ => MemberKind.Type,
    };

    public string FullName => RawName.Length > 2 ? RawName[2..] : RawName;

    public string FullTypeName
    {
        get
        {
            if (Kind == MemberKind.Type) return FullName;
            var name = FullName;
            var parenIdx = name.IndexOf('(');
            if (parenIdx >= 0) name = name[..parenIdx];
            var lastDot = name.LastIndexOf('.');
            return lastDot >= 0 ? name[..lastDot] : name;
        }
    }

    public string Namespace
    {
        get
        {
            var typeName = Kind == MemberKind.Type ? FullName : FullTypeName;
            var clean = typeName;
            var btIdx = clean.IndexOf('`');
            if (btIdx >= 0) clean = clean[..btIdx];
            var lastDot = clean.LastIndexOf('.');
            return lastDot >= 0 ? clean[..lastDot] : "";
        }
    }

    public string TypeName
    {
        get
        {
            var typeName = Kind == MemberKind.Type ? FullName : FullTypeName;
            var lastDot = typeName.LastIndexOf('.');
            var name = lastDot >= 0 ? typeName[(lastDot + 1)..] : typeName;
            return CleanGeneric(name);
        }
    }

    public string DisplayTypeName => TypeName;

    public string MemberName
    {
        get
        {
            if (Kind == MemberKind.Type) return TypeName;
            var name = FullName;
            var parenIdx = name.IndexOf('(');
            if (parenIdx >= 0) name = name[..parenIdx];
            var lastDot = name.LastIndexOf('.');
            return lastDot >= 0 ? CleanGeneric(name[(lastDot + 1)..]) : CleanGeneric(name);
        }
    }

    public string DisplaySignature
    {
        get
        {
            if (Kind == MemberKind.Property)
                return $"{MemberName} {{ get; }}";

            if (Kind == MemberKind.Method)
            {
                var paramElements = Element.Elements("param").ToList();
                var paramList = string.Join(", ", paramElements.Select(p => p.Attribute("name")?.Value ?? "?"));
                return $"{MemberName}({paramList})";
            }

            return MemberName;
        }
    }

    private static string CleanGeneric(string name)
    {
        var idx = name.IndexOf('`');
        if (idx >= 0) return $"{name[..idx]}<T>";
        return name;
    }
}
