using System.Reflection;
using System.Runtime.Loader;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;

var config = args.Length > 0 ? args[0] : "Debug";
var repoRoot = FindRepoRoot();
var docInputs = new[]
{
    new ApiDocInput(
        Path.Combine(repoRoot, $"Alis.Reactive/bin/{config}/net10.0/Alis.Reactive.xml"),
        Path.Combine(repoRoot, $"Alis.Reactive/bin/{config}/net10.0/Alis.Reactive.dll")),
    new ApiDocInput(
        Path.Combine(repoRoot, $"Alis.Reactive.Native/bin/{config}/net10.0/Alis.Reactive.Native.xml"),
        Path.Combine(repoRoot, $"Alis.Reactive.Native/bin/{config}/net10.0/Alis.Reactive.Native.dll")),
    new ApiDocInput(
        Path.Combine(repoRoot, $"Alis.Reactive.Fusion/bin/{config}/net10.0/Alis.Reactive.Fusion.xml"),
        Path.Combine(repoRoot, $"Alis.Reactive.Fusion/bin/{config}/net10.0/Alis.Reactive.Fusion.dll")),
};
var outputPath = Path.Combine(repoRoot, "docs-site/src/content/docs/reference/api-reference.md");
var publicSurface = PublicSurface.Load(docInputs);

var allMembers = new List<DocMember>();
foreach (var input in docInputs)
{
    if (!File.Exists(input.XmlFile))
    {
        Console.Error.WriteLine($"WARNING: XML file not found: {input.XmlFile}");
        Console.Error.WriteLine("Run 'dotnet build' first to generate XML documentation files.");
        continue;
    }

    var doc = XDocument.Load(input.XmlFile);
    var assemblyName = doc.Root?.Element("assembly")?.Element("name")?.Value ?? "Unknown";

    foreach (var member in doc.Descendants("member"))
    {
        var name = member.Attribute("name")?.Value;
        if (string.IsNullOrEmpty(name)) continue;

        allMembers.Add(new DocMember(
            name,
            assemblyName,
            member,
            publicSurface.ParameterNames(name),
            publicSurface.ParameterTypes(name)));
    }
}

if (allMembers.Count == 0)
{
    Console.Error.WriteLine("ERROR: No XML documentation members found. Run 'dotnet build' first.");
    return 1;
}

var publicMembers = allMembers
    .Where(publicSurface.Contains)
    .Where(m => !IsInternal(m))
    .ToList();

var types = publicMembers
    .Where(m => m.Kind == MemberKind.Type)
    .OrderBy(m => m.Namespace)
    .ThenBy(m => m.TypeName)
    .ToList();

var membersByType = publicMembers
    .Where(m => m.Kind != MemberKind.Type)
    .GroupBy(m => m.FullTypeName)
    .ToDictionary(g => g.Key, g => g.OrderBy(m => m.MemberName).ToList());

var markdown = new StringBuilder();
markdown.AppendLine("---");
markdown.AppendLine("title: API Reference");
markdown.AppendLine("description: Complete public API — every method, every overload, every signature. Auto-generated from XML documentation.");
markdown.AppendLine("sidebar:");
markdown.AppendLine("  order: 0");
markdown.AppendLine("---");
markdown.AppendLine();
markdown.AppendLine("<!-- AUTO-GENERATED by tools/ApiDocGenerator. Do not edit manually. -->");
markdown.AppendLine("<!-- Run: npm run build:api-docs -->");
markdown.AppendLine();
markdown.AppendLine("Complete public API for Alis.Reactive. Auto-generated from XML documentation comments.");
markdown.AppendLine("For usage and examples, see the [Grammar Tree](../../csharp-modules/mental-model/#the-grammar-tree) and the [Reactivity](../../csharp-modules/reactivity/triggers-and-reactions/) pages.");
markdown.AppendLine();

var byAssembly = types.GroupBy(t => t.Assembly).OrderBy(g => g.Key);
foreach (var assemblyGroup in byAssembly)
{
    var byNamespace = assemblyGroup.GroupBy(t => t.Namespace).OrderBy(g => g.Key);
    foreach (var nsGroup in byNamespace)
    {
        markdown.AppendLine($"## {SimplifyNamespace(nsGroup.Key)}");
        markdown.AppendLine();

        foreach (var docType in nsGroup)
        {
            markdown.AppendLine($"### {docType.DisplayTypeName}");
            markdown.AppendLine();

            var summary = GetSummaryText(docType.Element);
            if (!string.IsNullOrWhiteSpace(summary))
            {
                markdown.AppendLine(summary.Trim());
                markdown.AppendLine();
            }

            if (membersByType.TryGetValue(docType.FullTypeName, out var members))
            {
                var properties = members.Where(m => m.Kind == MemberKind.Property).ToList();
                var methods = members.Where(m => m.Kind == MemberKind.Method).ToList();

                if (properties.Count > 0)
                {
                    markdown.AppendLine("```csharp");
                    markdown.AppendLine("// Properties");
                    foreach (var property in properties)
                    {
                        var propertySummary = GetSummaryInline(property.Element);
                        markdown.AppendLine(string.IsNullOrWhiteSpace(propertySummary)
                            ? property.DisplaySignature
                            : $"{property.DisplaySignature}  // {propertySummary}");
                    }
                    markdown.AppendLine("```");
                    markdown.AppendLine();
                }

                if (methods.Count > 0)
                {
                    markdown.AppendLine("```csharp");
                    foreach (var method in DisplayMethods(methods))
                    {
                        markdown.AppendLine(method);
                    }
                    markdown.AppendLine("```");
                    markdown.AppendLine();
                }
            }
        }

        markdown.AppendLine("---");
        markdown.AppendLine();
    }
}

var outputDir = Path.GetDirectoryName(outputPath)!;
Directory.CreateDirectory(outputDir);
File.WriteAllText(outputPath, markdown.ToString().TrimEnd() + Environment.NewLine);

Console.WriteLine($"Generated API reference: {outputPath}");
Console.WriteLine($"  Types: {types.Count}");
Console.WriteLine($"  Members: {publicMembers.Count - types.Count}");
Console.WriteLine($"  From: {docInputs.Length} XML files");

return 0;

static string FindRepoRoot()
{
    var dir = Directory.GetCurrentDirectory();
    while (dir != null)
    {
        if (File.Exists(Path.Combine(dir, "package.json")) &&
            Directory.Exists(Path.Combine(dir, "Alis.Reactive")))
            return dir;
        dir = Directory.GetParent(dir)?.FullName;
    }
    return Directory.GetCurrentDirectory();
}

static bool IsInternal(DocMember m)
{
    var summary = m.Element.Element("summary")?.Value ?? "";
    if (summary.Contains("NEVER make public", StringComparison.OrdinalIgnoreCase))
        return true;
    if (m.Kind == MemberKind.Method && m.MemberName == "#ctor")
        return true;
    return false;
}

static string GetSummaryText(XElement member)
{
    var summary = member.Element("summary");
    if (summary == null) return "";
    return NormalizeDocText(CleanXmlText(summary));
}

static string GetSummaryInline(XElement member)
{
    var summary = member.Element("summary");
    if (summary == null) return "";
    return string.Join(" ", NormalizeDocText(CleanXmlText(summary))
        .Split('\n')
        .Select(line => line.Trim()));
}

static string NormalizeDocText(string text)
{
    var lines = text.Replace("\r\n", "\n").Split('\n')
        .Select(line => line.Trim())
        .ToList();

    while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[0]))
        lines.RemoveAt(0);

    while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[^1]))
        lines.RemoveAt(lines.Count - 1);

    return string.Join(Environment.NewLine, lines);
}

static string CleanXmlText(XElement element)
{
    var markdown = new StringBuilder();
    foreach (var xmlNode in element.Nodes())
    {
        if (xmlNode is XText text)
        {
            markdown.Append(text.Value);
        }
        else if (xmlNode is XElement xmlElement)
        {
            switch (xmlElement.Name.LocalName)
            {
                case "c":
                    markdown.Append($"`{xmlElement.Value}`");
                    break;
                case "code":
                    markdown.AppendLine();
                    markdown.AppendLine("```csharp");
                    markdown.AppendLine(xmlElement.Value.Trim());
                    markdown.AppendLine("```");
                    break;
                case "see":
                    var cref = xmlElement.Attribute("cref")?.Value;
                    var langword = xmlElement.Attribute("langword")?.Value;
                    if (langword != null)
                        markdown.Append($"`{langword}`");
                    else if (cref != null)
                        markdown.Append($"`{SimplifyCref(cref)}`");
                    else
                        markdown.Append(xmlElement.Value);
                    break;
                case "para":
                    markdown.AppendLine();
                    markdown.Append(CleanXmlText(xmlElement));
                    break;
                case "paramref":
                    markdown.Append($"`{xmlElement.Attribute("name")?.Value}`");
                    break;
                case "typeparamref":
                    markdown.Append($"`{xmlElement.Attribute("name")?.Value}`");
                    break;
                case "b":
                    markdown.Append($"**{xmlElement.Value}**");
                    break;
                default:
                    markdown.Append(CleanXmlText(xmlElement));
                    break;
            }
        }
    }
    return markdown.ToString();
}

static string SimplifyCref(string cref)
{
    if (cref.Length > 2 && cref[1] == ':')
        cref = cref[2..];
    var parameterListIndex = cref.IndexOf('(');
    if (parameterListIndex >= 0)
        cref = cref[..parameterListIndex];
    var lastDot = cref.LastIndexOf('.');
    if (lastDot >= 0) cref = cref[(lastDot + 1)..];
    return CleanGenericNotation(cref);
}

static string SimplifyNamespace(string ns)
{
    return ns.Replace("Alis.Reactive.", "").Replace(".", " — ");
}

static IEnumerable<string> DisplayMethods(IReadOnlyList<DocMember> methods)
{
    var duplicateSignatures = methods
        .GroupBy(method => method.DisplaySignature)
        .Where(group => group.Count() > 1)
        .Select(group => group.Key)
        .ToHashSet(StringComparer.Ordinal);

    return methods.Select(method => duplicateSignatures.Contains(method.DisplaySignature) && method.CanDisplayParameterTypes
        ? method.DisplaySignatureWithParameterTypes
        : method.DisplaySignature);
}

static string CleanGenericNotation(string name)
{
    var genericBraceIndex = name.IndexOf('{');
    if (genericBraceIndex >= 0) return $"{name[..genericBraceIndex]}<T>";
    var genericArityMarkerIndex = name.IndexOf('`');
    if (genericArityMarkerIndex >= 0) return $"{name[..genericArityMarkerIndex]}<T>";
    return name;
}

enum MemberKind { Type, Method, Property, Field, Event }

record ApiDocInput(string XmlFile, string AssemblyFile);

sealed class PublicSurface
{
    private readonly Dictionary<string, PublicMemberMetadata> _members;

    private PublicSurface(Dictionary<string, PublicMemberMetadata> members)
    {
        _members = members;
    }

    public static PublicSurface Load(IEnumerable<ApiDocInput> inputs)
    {
        var members = new Dictionary<string, PublicMemberMetadata>(StringComparer.Ordinal);

        foreach (var input in inputs)
        {
            if (!File.Exists(input.AssemblyFile))
                continue;

            RegisterAssemblyResolver(input.AssemblyFile);
            var assembly = Assembly.LoadFrom(input.AssemblyFile);
            foreach (var type in GetLoadableTypes(assembly).Where(IsVisibleType))
            {
                members["T:" + type.FullName] = PublicMemberMetadata.None;
                AddVisibleMembers(members, type);
            }
        }

        return new PublicSurface(members);
    }

    public bool Contains(DocMember member) => _members.ContainsKey(member.RawName);

    public IReadOnlyList<string> ParameterNames(string memberId) =>
        _members.TryGetValue(memberId, out var metadata)
            ? metadata.ParameterNames
            : Array.Empty<string>();

    public IReadOnlyList<string> ParameterTypes(string memberId) =>
        _members.TryGetValue(memberId, out var metadata)
            ? metadata.ParameterTypes
            : Array.Empty<string>();

    private static void RegisterAssemblyResolver(string assemblyFile)
    {
        var resolver = new AssemblyDependencyResolver(assemblyFile);
        AssemblyLoadContext.Default.Resolving += (_, assemblyName) =>
        {
            var resolvedPath = resolver.ResolveAssemblyToPath(assemblyName)
                ?? ResolveFromTrustedPlatformAssemblies(assemblyName)
                ?? ResolveFromNuGetPackages(assemblyName)
                ?? ResolveFromAnyNuGetPackage(assemblyName)
                ?? ResolveFromDotNetSharedFramework(assemblyName);
            return resolvedPath == null ? null : Assembly.LoadFrom(resolvedPath);
        };
    }

    private static string? ResolveFromTrustedPlatformAssemblies(AssemblyName assemblyName)
    {
        var trustedAssemblies = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (trustedAssemblies == null)
            return null;

        var assemblyFileName = assemblyName.Name + ".dll";
        return trustedAssemblies
            .Split(Path.PathSeparator)
            .FirstOrDefault(path => string.Equals(Path.GetFileName(path), assemblyFileName, StringComparison.OrdinalIgnoreCase));
    }

    private static string? ResolveFromNuGetPackages(AssemblyName assemblyName)
    {
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        var packageRoot = Path.Combine(home, ".nuget", "packages", assemblyName.Name!.ToLowerInvariant());
        if (!Directory.Exists(packageRoot))
            return null;

        return Directory
            .EnumerateFiles(packageRoot, assemblyName.Name + ".dll", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .LastOrDefault();
    }

    private static string? ResolveFromAnyNuGetPackage(AssemblyName assemblyName)
    {
        var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        var packagesRoot = Path.Combine(home, ".nuget", "packages");
        if (!Directory.Exists(packagesRoot))
            return null;

        return Directory
            .EnumerateFiles(packagesRoot, assemblyName.Name + ".dll", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .LastOrDefault();
    }

    private static string? ResolveFromDotNetSharedFramework(AssemblyName assemblyName)
    {
        var runtimeDirectory = RuntimeEnvironment.GetRuntimeDirectory();
        var sharedRoot = Directory.GetParent(runtimeDirectory)?.Parent?.FullName;
        if (sharedRoot == null || !Directory.Exists(sharedRoot))
            return null;

        return Directory
            .EnumerateFiles(sharedRoot, assemblyName.Name + ".dll", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .LastOrDefault();
    }

    private static IEnumerable<Type> GetLoadableTypes(Assembly assembly)
    {
        try
        {
            return assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            return ex.Types.Where(type => type != null)!;
        }
    }

    private static bool IsVisibleType(Type type) =>
        type.IsVisible;

    private static void AddVisibleMembers(Dictionary<string, PublicMemberMetadata> members, Type type)
    {
        const BindingFlags flags =
            BindingFlags.Instance |
            BindingFlags.Static |
            BindingFlags.Public |
            BindingFlags.NonPublic |
            BindingFlags.DeclaredOnly;

        foreach (var constructor in type.GetConstructors(flags).Where(IsVisibleMethod))
            AddMethod(members, type, constructor);

        foreach (var method in type.GetMethods(flags).Where(IsVisibleMethod))
            AddMethod(members, type, method);

        foreach (var property in type.GetProperties(flags).Where(IsVisibleProperty))
            members["P:" + type.FullName + "." + property.Name] = PublicMemberMetadata.None;

        foreach (var field in type.GetFields(flags).Where(IsVisibleField))
            members["F:" + type.FullName + "." + field.Name] = PublicMemberMetadata.None;

        foreach (var eventInfo in type.GetEvents(flags).Where(IsVisibleEvent))
            members["E:" + type.FullName + "." + eventInfo.Name] = PublicMemberMetadata.None;
    }

    private static void AddMethod(Dictionary<string, PublicMemberMetadata> members, Type type, MethodBase method)
    {
        var parameters = method.GetParameters();
        var parameterNames = parameters
            .Select(parameter => parameter.Name ?? "?")
            .ToArray();
        var parameterTypes = parameters
            .Select(parameter => DisplayParameterType(parameter.ParameterType))
            .ToArray();
        members[MethodId(type, method)] = new PublicMemberMetadata(parameterNames, parameterTypes);
    }

    private static bool IsVisibleMethod(MethodBase method) =>
        method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;

    private static bool IsVisibleProperty(PropertyInfo property)
    {
        var accessors = property.GetAccessors(nonPublic: true);
        return accessors.Any(IsVisibleMethod);
    }

    private static bool IsVisibleField(FieldInfo field) =>
        field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;

    private static bool IsVisibleEvent(EventInfo eventInfo)
    {
        var add = eventInfo.GetAddMethod(nonPublic: true);
        var remove = eventInfo.GetRemoveMethod(nonPublic: true);
        return (add != null && IsVisibleMethod(add)) || (remove != null && IsVisibleMethod(remove));
    }

    private static string MethodId(Type declaringType, MethodBase method)
    {
        var name = method.IsConstructor ? "#ctor" : method.Name;
        if (method is MethodInfo { IsGenericMethod: true } methodInfo)
            name += "``" + methodInfo.GetGenericArguments().Length;

        var parameters = method.GetParameters();
        return parameters.Length == 0
            ? $"M:{declaringType.FullName}.{name}"
            : $"M:{declaringType.FullName}.{name}({string.Join(",", parameters.Select(parameter => TypeId(parameter.ParameterType)))})";
    }

    private static string TypeId(Type type)
    {
        if (type.IsGenericParameter)
            return (type.DeclaringMethod == null ? "`" : "``") + type.GenericParameterPosition;

        if (type.IsByRef)
            return TypeId(type.GetElementType()!) + "@";

        if (type.IsArray)
            return TypeId(type.GetElementType()!) + "[]";

        if (!type.IsGenericType)
            return type.FullName ?? type.Name;

        var genericDefinitionName = type.GetGenericTypeDefinition().FullName!;
        var genericMarker = genericDefinitionName.IndexOf('`');
        if (genericMarker >= 0)
            genericDefinitionName = genericDefinitionName[..genericMarker];

        return genericDefinitionName + "{" + string.Join(",", type.GetGenericArguments().Select(TypeId)) + "}";
    }

    private static string DisplayParameterType(Type type)
    {
        if (type.IsByRef)
            return DisplayParameterType(type.GetElementType()!) + "&";

        if (type.IsArray)
            return DisplayParameterType(type.GetElementType()!) + "[]";

        if (type.IsGenericParameter)
            return type.Name;

        if (!type.IsGenericType)
            return SimplifyKnownType(type) ?? StripNamespace(type.FullName ?? type.Name);

        var genericDefinitionName = type.GetGenericTypeDefinition().FullName ?? type.Name;
        var genericMarker = genericDefinitionName.IndexOf('`');
        if (genericMarker >= 0)
            genericDefinitionName = genericDefinitionName[..genericMarker];

        return StripNamespace(genericDefinitionName) +
            "<" + string.Join(", ", type.GetGenericArguments().Select(DisplayParameterType)) + ">";
    }

    private static string? SimplifyKnownType(Type type) =>
        type.FullName switch
        {
            "System.String" => "string",
            "System.Int32" => "int",
            "System.Int64" => "long",
            "System.Boolean" => "bool",
            "System.Decimal" => "decimal",
            "System.Double" => "double",
            "System.DateTime" => "DateTime",
            "System.Object" => "object",
            _ => null,
        };

    private static string StripNamespace(string name)
    {
        var nestedTypeMarker = name.LastIndexOf('+');
        if (nestedTypeMarker >= 0)
            name = name[(nestedTypeMarker + 1)..];

        var lastDot = name.LastIndexOf('.');
        return lastDot >= 0 ? name[(lastDot + 1)..] : name;
    }
}

record PublicMemberMetadata(IReadOnlyList<string> ParameterNames, IReadOnlyList<string> ParameterTypes)
{
    public static PublicMemberMetadata None { get; } = new(Array.Empty<string>(), Array.Empty<string>());
}

record DocMember(
    string RawName,
    string Assembly,
    XElement Element,
    IReadOnlyList<string> ReflectedParameterNames,
    IReadOnlyList<string> ReflectedParameterTypes)
{
    public MemberKind Kind => RawName[0] switch
    {
        'T' => MemberKind.Type,
        'M' => MemberKind.Method,
        'P' => MemberKind.Property,
        'F' => MemberKind.Field,
        'E' => MemberKind.Event,
        _ => MemberKind.Type,
    };

    public string FullName => RawName.Length > 2 ? RawName[2..] : RawName;

    public string FullTypeName
    {
        get
        {
            if (Kind == MemberKind.Type) return FullName;
            var name = FullName;
            var parameterListIndex = name.IndexOf('(');
            if (parameterListIndex >= 0) name = name[..parameterListIndex];
            var lastDot = name.LastIndexOf('.');
            return lastDot >= 0 ? name[..lastDot] : name;
        }
    }

    public string Namespace
    {
        get
        {
            var typeName = Kind == MemberKind.Type ? FullName : FullTypeName;
            var clean = typeName;
            var genericArityMarkerIndex = clean.IndexOf('`');
            if (genericArityMarkerIndex >= 0) clean = clean[..genericArityMarkerIndex];
            var lastDot = clean.LastIndexOf('.');
            return lastDot >= 0 ? clean[..lastDot] : "";
        }
    }

    public string TypeName
    {
        get
        {
            var typeName = Kind == MemberKind.Type ? FullName : FullTypeName;
            var lastDot = typeName.LastIndexOf('.');
            var name = lastDot >= 0 ? typeName[(lastDot + 1)..] : typeName;
            return CleanGeneric(name);
        }
    }

    public string DisplayTypeName => TypeName;

    public string MemberName
    {
        get
        {
            if (Kind == MemberKind.Type) return TypeName;
            var name = FullName;
            var parameterListIndex = name.IndexOf('(');
            if (parameterListIndex >= 0) name = name[..parameterListIndex];
            var lastDot = name.LastIndexOf('.');
            return lastDot >= 0 ? CleanGeneric(name[(lastDot + 1)..]) : CleanGeneric(name);
        }
    }

    public string DisplaySignature
    {
        get
        {
            if (Kind == MemberKind.Property)
                return $"{MemberName} {{ get; }}";

            if (Kind == MemberKind.Method)
            {
                var paramList = string.Join(", ", DisplayParameterNames());
                return $"{MemberName}({paramList})";
            }

            return MemberName;
        }
    }

    public string DisplaySignatureWithParameterTypes
    {
        get
        {
            if (Kind != MemberKind.Method)
                return DisplaySignature;

            var parameterNames = DisplayParameterNames();
            var parameterTypes = DisplayParameterTypes();
            var parameters = parameterNames
                .Select((name, index) =>
                {
                    return index < parameterTypes.Count
                        ? $"{parameterTypes[index]} {name}"
                        : name;
                });

            return $"{MemberName}({string.Join(", ", parameters)})";
        }
    }

    public bool CanDisplayParameterTypes =>
        DisplayParameterTypes().Count == DisplayParameterNames().Count;

    private List<string> DisplayParameterNames()
    {
        var parameterNames = ParameterNames();
        if (!IsExtensionContainer() || parameterNames.Count == 0)
            return parameterNames;

        var firstParamName = parameterNames[0];
        return IsExtensionReceiverName(firstParamName)
            ? parameterNames.Skip(1).ToList()
            : parameterNames;
    }

    private List<string> ParameterNames()
    {
        var xmlNames = Element.Elements("param")
            .Select(parameter => parameter.Attribute("name")?.Value)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Select(name => name!)
            .ToList();

        return xmlNames.Count > 0 || ReflectedParameterNames.Count == 0
            ? xmlNames
            : ReflectedParameterNames.ToList();
    }

    private List<string> DisplaySimpleParameterTypes()
    {
        var parameterTypes = RawParameterTypes();
        if (!IsExtensionContainer() || parameterTypes.Count == 0)
            return SimplifySimpleParameterTypes(parameterTypes);

        var firstParamName = ParameterNames().FirstOrDefault();
        parameterTypes = IsExtensionReceiverName(firstParamName)
            ? parameterTypes.Skip(1).ToList()
            : parameterTypes;

        return SimplifySimpleParameterTypes(parameterTypes);
    }

    private List<string> DisplayParameterTypes()
    {
        if (ReflectedParameterTypes.Count > 0)
        {
            var parameterTypes = ReflectedParameterTypes.ToList();
            if (IsExtensionContainer() &&
                parameterTypes.Count > 0 &&
                IsExtensionReceiverName(ReflectedParameterNames.FirstOrDefault()))
            {
                parameterTypes = parameterTypes.Skip(1).ToList();
            }

            return parameterTypes;
        }

        return DisplaySimpleParameterTypes();
    }

    private static List<string> SimplifySimpleParameterTypes(IEnumerable<string> parameterTypes)
    {
        var simpleTypes = new List<string>();
        foreach (var parameterType in parameterTypes)
        {
            var simpleType = SimplifySimpleParameterType(parameterType);
            if (simpleType == null)
                return new List<string>();
            simpleTypes.Add(simpleType);
        }

        return simpleTypes;
    }

    private List<string> RawParameterTypes()
    {
        var start = FullName.IndexOf('(');
        if (start < 0 || !FullName.EndsWith(")", StringComparison.Ordinal))
            return new List<string>();

        var parameters = FullName[(start + 1)..^1];
        if (string.IsNullOrWhiteSpace(parameters))
            return new List<string>();

        return SplitParameterTypes(parameters).ToList();
    }

    private static IEnumerable<string> SplitParameterTypes(string parameters)
    {
        var start = 0;
        var depth = 0;
        for (var i = 0; i < parameters.Length; i++)
        {
            var ch = parameters[i];
            if (ch == '{')
                depth++;
            else if (ch == '}')
                depth--;
            else if (ch == ',' && depth == 0)
            {
                yield return parameters[start..i];
                start = i + 1;
            }
        }

        yield return parameters[start..];
    }

    private static string? SimplifySimpleParameterType(string type)
    {
        type = type.Trim();

        return type switch
        {
            "System.String" => "string",
            "System.Int32" => "int",
            "System.Int64" => "long",
            "System.Boolean" => "bool",
            "System.Decimal" => "decimal",
            "System.Double" => "double",
            "System.DateTime" => "DateTime",
            _ => null,
        };
    }

    private bool IsExtensionContainer() =>
        TypeName.EndsWith("Extensions", StringComparison.Ordinal);

    private static bool IsExtensionReceiverName(string? parameterName) =>
        parameterName is "html" or "self" or "builder" or "services" or "args";

    private static string CleanGeneric(string name)
    {
        var genericBraceIndex = name.IndexOf('{');
        if (genericBraceIndex >= 0) return $"{name[..genericBraceIndex]}<T>";
        var genericArityMarkerIndex = name.IndexOf('`');
        if (genericArityMarkerIndex >= 0) return $"{name[..genericArityMarkerIndex]}<T>";
        return name;
    }
}
